class_name SuspensionTable
extends RefCounted
## SUS-GEO-07: validated pose tables unifying physics and visuals.
##
## The Rust solver stays the authority for forces. Godot renders from the SAME
## validated data: per-corner tables generated by the `build_geo_table` example
## from the physical geometry (see `suspension_table.rs`, schema
## `geometry_table/1`). This reader interpolates bilinearly with the EXACT same
## math as `CornerTable::sample` (mirror it line-by-line when touching either
## side), clamped to the validated envelope, so physics and visuals cannot
## diverge. It replaces the PBD solver + visual travel clamps for geometric
## profiles only; legacy `suspension.geometry` visuals keep SuspensionGeometry.
##
## Table file: {"version": 1, "tables": {"FrontLeft": CornerTable, ...}} where
## CornerTable = {"version":1, "wheel":"FrontLeft", "q_min","q_max","n_q",
## "rack_min","rack_max","n_rack", "samples": flatten(samples[q][rack])} and a
## sample = {"hub":{"x","y","z"}, "upright":{"x":{},"y":{},"z":{}},
## "rocker_angle","damper_length","camber_link","toe_link"}.

const TABLE_VERSION := 1

var wheel: String = ""
var q_min: float = 0.0
var q_max: float = 0.0
var n_q: int = 0
var rack_min: float = 0.0
var rack_max: float = 0.0
var n_rack: int = 0
var samples: Array = []


static func _vec(d: Dictionary) -> Vector3:
	return Vector3(float(d.get("x", 0.0)), float(d.get("y", 0.0)), float(d.get("z", 0.0)))


static func _basis(d: Dictionary) -> Basis:
	var bx: Vector3 = _vec(d.get("x", {}))
	var by: Vector3 = _vec(d.get("y", {}))
	var bz: Vector3 = _vec(d.get("z", {}))
	return Basis(bx, by, bz)


static func from_dict(wheel_name: String, d: Dictionary) -> SuspensionTable:
	var t := SuspensionTable.new()
	t.wheel = wheel_name
	if int(d.get("version", 0)) != TABLE_VERSION:
		push_error("SuspensionTable: bad version for " + wheel_name)
		return null
	t.q_min = float(d.get("q_min", 0.0))
	t.q_max = float(d.get("q_max", 0.0))
	t.n_q = int(d.get("n_q", 0))
	t.rack_min = float(d.get("rack_min", 0.0))
	t.rack_max = float(d.get("rack_max", 0.0))
	t.n_rack = int(d.get("n_rack", 0))
	t.samples = d.get("samples", []) as Array
	if t.n_q < 2 or t.n_rack < 1 or t.samples.size() != t.n_q * t.n_rack:
		push_error("SuspensionTable: sample count mismatch for " + wheel_name)
		return null
	return t


static func load_tables(path: String) -> Dictionary:
	# Returns {"FrontLeft": SuspensionTable, ...} or {} on any error.
	var out := {}
	if not FileAccess.file_exists(path):
		return out
	var text: String = FileAccess.get_file_as_string(path)
	var parsed: Variant = JSON.parse_string(text)
	if typeof(parsed) != TYPE_DICTIONARY:
		push_error("SuspensionTable: invalid JSON " + path)
		return out
	var root: Dictionary = parsed
	if int(root.get("version", 0)) != TABLE_VERSION:
		push_error("SuspensionTable: bad file version " + path)
		return out
	var tables: Dictionary = root.get("tables", {})
	for wheel_name in tables.keys():
		var t: SuspensionTable = SuspensionTable.from_dict(str(wheel_name), tables[wheel_name])
		if t != null:
			out[str(wheel_name)] = t
	return out


func _grid_pos(q: float, rack: float) -> Vector2:
	var qq: float = q if is_finite(q) else 0.0
	var rr: float = rack if is_finite(rack) else 0.0
	var fq := 0.0
	var fr := 0.0
	if n_q >= 2 and q_max > q_min:
		fq = (clampf(qq, q_min, q_max) - q_min) / (q_max - q_min) * float(n_q - 1)
	if n_rack >= 2 and rack_max > rack_min:
		fr = (clampf(rr, rack_min, rack_max) - rack_min) / (rack_max - rack_min) * float(n_rack - 1)
	return Vector2(fq, fr)


func _at(iq: int, ir: int) -> Dictionary:
	return samples[iq * n_rack + ir] as Dictionary


static func _lerp_f(x0: float, x1: float, t: float) -> float:
	return x0 + (x1 - x0) * t


## Bilinear sample, clamped to the validated envelope. Mirrors
## `CornerTable::sample` exactly (same node order, same weights).
func sample_pose(q: float, rack: float) -> Dictionary:
	var g := _grid_pos(q, rack)
	var q0: int = mini(int(floor(g.x)), n_q - 1)
	var q1: int = mini(q0 + 1, n_q - 1)
	var r0: int = mini(int(floor(g.y)), n_rack - 1)
	var r1: int = mini(r0 + 1, n_rack - 1)
	var tq: float = g.x - float(q0)
	var tr: float = g.y - float(r0)
	var a := _at(q0, r0)
	var b := _at(q1, r0)
	var c := _at(q0, r1)
	var d := _at(q1, r1)
	var ah := _vec(a["hub"])
	var bh := _vec(b["hub"])
	var ch := _vec(c["hub"])
	var dh := _vec(d["hub"])
	var hub := ah.lerp(bh, tq).lerp(ch.lerp(dh, tq), tr)
	var ab := _basis(a["upright"])
	var bb := _basis(b["upright"])
	var cb := _basis(c["upright"])
	var db := _basis(d["upright"])
	var bx := ab.x.lerp(bb.x, tq).lerp(cb.x.lerp(db.x, tq), tr)
	var by := ab.y.lerp(bb.y, tq).lerp(cb.y.lerp(db.y, tq), tr)
	var upright := _orthonormalize(bx, by)
	return {
		"hub": hub,
		"upright": upright,
		"rocker_angle": _bilin(a, b, c, d, "rocker_angle", tq, tr),
		"damper_length": _bilin(a, b, c, d, "damper_length", tq, tr),
		"camber_link": _bilin(a, b, c, d, "camber_link", tq, tr),
		"toe_link": _bilin(a, b, c, d, "toe_link", tq, tr),
	}


static func _bilin(a: Dictionary, b: Dictionary, c: Dictionary, d: Dictionary, key: String, tq: float, tr: float) -> float:
	var ab: float = _lerp_f(float(a[key]), float(b[key]), tq)
	var cd: float = _lerp_f(float(c[key]), float(d[key]), tq)
	return _lerp_f(ab, cd, tr)


static func _orthonormalize(bx: Vector3, by: Vector3) -> Basis:
	# Same Gram-Schmidt as Rust `orthonormalize_cols`.
	var x := bx.normalized() if bx.length_squared() > 1e-12 else Vector3.RIGHT
	var y := by - x * by.dot(x)
	if y.length_squared() < 1e-12:
		y = Vector3.UP - x * Vector3.UP.dot(x)
		if y.length_squared() < 1e-12:
			y = Vector3.FORWARD
	y = y.normalized()
	var z := x.cross(y).normalized()
	x = y.cross(z).normalized()
	return Basis(x, y, z)
