//! Rust<->Python centerline parity test.
//!
//! The golden fixture is generated by `generate_centerline_golden.py` using the
//! exact production Python code paths (svg_sanitizer + svg_normalizer). This
//! test asserts that the Rust resampling and length computation reproduce the
//! Python normalizer contract for the compile_track.svg fixture.

use serde::Deserialize;
use track_geometry::{closed_polyline_length, parse_path, resample_closed_polyline, Point2};

#[derive(Deserialize)]
struct Golden {
    sample_spacing_m: f64,
    centerline_d: String,
    raw_polyline: Vec<[f64; 2]>,
    resampled_polyline: Vec<[f64; 2]>,
    raw_length_m: f64,
    resampled_length_m: f64,
    resampled_count: usize,
}

fn golden(fixture: &str) -> Golden {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/").to_owned()
        + fixture
        + "_centerline.golden.json";
    let text = std::fs::read_to_string(&path).expect("golden fixture must exist");
    serde_json::from_str(&text).expect("golden fixture must be valid JSON")
}

fn points(polyline: &[[f64; 2]]) -> Vec<Point2> {
    polyline
        .iter()
        .map(|[x, z]| Point2 { x: *x, z: *z })
        .collect()
}

fn round6(value: f64) -> f64 {
    (value * 1e6).round() / 1e6
}

#[test]
fn rust_resampling_matches_python_normalizer_fixture() {
    let fixture = golden("compile_track");
    let raw = points(&fixture.raw_polyline);
    let resampled = resample_closed_polyline(&raw, fixture.sample_spacing_m).unwrap();

    assert_eq!(resampled.len(), fixture.resampled_count);
    assert_eq!(resampled.len(), fixture.resampled_polyline.len());
    for (rust, python) in resampled.iter().zip(&fixture.resampled_polyline) {
        assert!(
            (round6(rust.x) - python[0]).abs() < 1e-9,
            "resampled x mismatch: {} != {}",
            round6(rust.x),
            python[0]
        );
        assert!(
            (round6(rust.z) - python[1]).abs() < 1e-9,
            "resampled z mismatch: {} != {}",
            round6(rust.z),
            python[1]
        );
    }
}

#[test]
fn rust_lengths_match_python_normalizer_fixture() {
    let fixture = golden("compile_track");
    let raw = points(&fixture.raw_polyline);

    let rust_raw = closed_polyline_length(&raw).unwrap();
    assert!(
        (rust_raw - fixture.raw_length_m).abs() < 1e-9,
        "raw length mismatch: {rust_raw} != {}",
        fixture.raw_length_m
    );

    let resampled = resample_closed_polyline(&raw, fixture.sample_spacing_m).unwrap();
    let rust_resampled = closed_polyline_length(&resampled).unwrap();
    assert!(
        (rust_resampled - fixture.resampled_length_m).abs() < 1e-6,
        "resampled length mismatch: {rust_resampled} != {}",
        fixture.resampled_length_m
    );
}

#[test]
fn rust_path_parsing_matches_python_flatten_for_curves() {
    let fixture = golden("curve_track");
    let subpaths = parse_path(&fixture.centerline_d, 0.1).unwrap();
    assert_eq!(subpaths.len(), 1);

    let rust = &subpaths[0];
    let python = points(&fixture.raw_polyline);
    assert_eq!(rust.len(), python.len());
    for (rust, python) in rust.iter().zip(&python) {
        assert!(
            (rust.x - python.x).abs() < 1e-9,
            "flatten x mismatch: {} != {}",
            rust.x,
            python.x
        );
        assert!(
            (rust.z - python.z).abs() < 1e-9,
            "flatten z mismatch: {} != {}",
            rust.z,
            python.z
        );
    }

    let rust_length = closed_polyline_length(rust).unwrap();
    assert!(
        (rust_length - fixture.raw_length_m).abs() < 1e-9,
        "curve raw length mismatch: {rust_length} != {}",
        fixture.raw_length_m
    );
}
