//! Orchestrated frame: the atomic outcome of one `CoreFacade::step`.
//!
//! Every tick the facade produces a single `CoreFrame` carrying physics force/torque,
//! the compact telemetry (`EntityTelemetry`), audio readouts and per-module outputs.
//! Mirrors (C++ `F90Core` node, headless `core_cli`) consume this frame; the audio
//! render pulls from the same frame so audio never sees stale phyics.

use serde::{Deserialize, Serialize};

/// Surface codes mirrored in `native/include/formula90s/core/f90_core.h`.
pub const SURFACE_ASPHALT: u8 = 0;
pub const SURFACE_RUMBLE: u8 = 1;
pub const SURFACE_GRASS: u8 = 2;
pub const SURFACE_SAND: u8 = 3;

/// Active surface-bed codes mirrored in `f90_core.h`.
pub const BED_NONE: u8 = 0;
pub const BED_RUMBLE: u8 = 1;
pub const BED_GRASS: u8 = 2;
pub const BED_SAND: u8 = 3;

/// Audio presentation readouts a HUD/telemetry mirror needs (mirrors the legacy
/// `VehicleAudioControllerNative` getter surface).
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct AudioReadouts {
    pub surface_code: u8,
    pub active_bed_code: u8,
    /// One-shot trigger code (0..10, legacy mapping) or -1 if none this tick.
    pub trigger_code: i32,
    pub last_norm: f32,
    pub last_rpm: f64,
    pub last_throttle: f32,
    pub last_speed_kph: f64,
    pub last_slip: f32,
    pub last_engine_gain: f32,
    pub weights: [f32; 5],
    pub pitches: [f32; 5],
    pub scrape_gain: f32,
    pub scrape_pitch: f32,
    pub scrape_cursor: f64,
    pub tyre_scrub_gain: f32,
    pub tyre_scrub_pitch: f32,
    pub tyre_scrub_mode: u8,
    pub tyre_scrub_cursor: f64,
}

impl Default for AudioReadouts {
    fn default() -> Self {
        Self {
            surface_code: SURFACE_ASPHALT,
            active_bed_code: BED_NONE,
            trigger_code: -1,
            last_norm: 0.0,
            last_rpm: 0.0,
            last_throttle: 0.0,
            last_speed_kph: 0.0,
            last_slip: 0.0,
            last_engine_gain: 0.0,
            weights: [0.0; 5],
            pitches: [1.0; 5],
            scrape_gain: 0.0,
            scrape_pitch: 1.0,
            scrape_cursor: 0.0,
            tyre_scrub_gain: 0.0,
            tyre_scrub_pitch: 1.0,
            tyre_scrub_mode: 0,
            tyre_scrub_cursor: 0.0,
        }
    }
}

/// Serializable per-module contribution merged into the facade snapshot.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModuleOutput {
    pub name: String,
    pub payload: Vec<u8>,
}

/// The complete orchestrated outcome of one fixed step.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CoreFrame {
    pub time_ms: i64,
    pub force: [f64; 3],
    pub torque: [f64; 3],
    pub speed_kmh: f64,
    pub rpm: f64,
    pub gear: i32,
    pub steer: f64,
    pub throttle: f64,
    pub lat_g: f64,
    pub long_g: f64,
    pub vert_g: f64,
    pub fl_comp_mm: f64,
    pub fr_comp_mm: f64,
    pub rl_comp_mm: f64,
    pub rr_comp_mm: f64,
    pub front_slip: f64,
    pub rear_slip: f64,
    // Per-wheel tyre contact state used internally by the audio scrub voice.
    pub wheel_slip_ratio: [f64; 4],
    pub wheel_slip_angle_rad: [f64; 4],
    pub wheel_contact_fraction: [f64; 4],
    pub wheel_normal_force_n: [f64; 4],
    pub tc_enabled: bool,
    pub tc_eligible: bool,
    pub tc_active: bool,
    pub tc_gear_authority: f64,
    pub tc_slip_target: f64,
    pub tc_raw_cut_ratio: f64,
    pub tc_cut_ratio: f64,
    pub tc_slip_ratio: [f64; 4],
    pub wheel_drive_torque_pre_tc_nm: [f64; 4],
    pub wheel_drive_torque_nm: [f64; 4],
    pub drive_torque: f64,
    pub pre_tc_drive_power_w: f64,
    pub net_drive_power_w: f64,
    pub px: f64,
    pub py: f64,
    pub pz: f64,
    pub yaw: f64,
    pub lvx: f64,
    pub lvy: f64,
    pub lvz: f64,
    pub avx: f64,
    pub avy: f64,
    pub avz: f64,
    // Tire pressure + thermal (per wheel, WheelIndex order FL/FR/RL/RR).
    pub tire_pressure_kpa: [f64; 4],
    pub tire_tread_inner_c: [f64; 4],
    pub tire_tread_center_c: [f64; 4],
    pub tire_tread_outer_c: [f64; 4],
    pub tire_carcass_c: [f64; 4],
    pub tire_gas_c: [f64; 4],
    pub brake_disc_c: [f64; 4],
    pub brake_rim_c: [f64; 4],
    pub brake_efficiency: [f64; 4],
    pub duct_mass_flow_kg_s: [f64; 4],
    pub duct_drag_n: [f64; 4],
    pub total_brake_duct_drag_n: f64,
    pub brake_optimal_min_c: f64,
    pub brake_optimal_max_c: f64,
    pub brake_fade_start_c: f64,
    pub brake_critical_c: f64,
    pub brake_torque_nm: [f64; 4],
    pub brake_spin_pre_rad_s: [f64; 4],
    pub brake_spin_post_rad_s: [f64; 4],
    pub brake_power_w: [f64; 4],
    pub brake_energy_j: [f64; 4],
    // Lumped rotor cooling diagnostics (compact brake model).
    pub brake_natural_cooling_w_k: [f64; 4],
    pub brake_speed_cooling_w_k: [f64; 4],
    pub underfloor_clearance_m: [f64; 5],
    pub underfloor_valid_mask: u32,
    pub underfloor_scrape_phase: i32,
    pub underfloor_min_clearance_m: f64,
    pub underfloor_rake_rad: f64,
    pub underfloor_roll_rad: f64,
    pub underfloor_contact_confidence: f64,
    pub underfloor_scrape_intensity: f64,
    pub underfloor_compression_m: [f64; 5],
    pub underfloor_closing_speed_m_s: [f64; 5],
    pub underfloor_normal_force_n: [f64; 5],
    pub underfloor_bottoming_phase: [i32; 5],
    pub underfloor_active_probe_mask: u32,
    pub underfloor_total_normal_force_n: f64,
    pub underfloor_max_probe_force_n: f64,
    pub underfloor_force_center_local: [f64; 3],
    pub underfloor_bottoming_torque: [f64; 3],
    pub underfloor_dissipated_energy_j: f64,
    pub underfloor_rigid_contact_blend: f64,
    // Element-level aerodynamics diagnostics.
    pub aero_total_downforce_n: f64,
    pub aero_raw_downforce_n: f64,
    pub aero_front_downforce_n: f64,
    pub aero_floor_downforce_n: f64,
    pub aero_rear_downforce_n: f64,
    pub aero_drag_n: f64,
    pub aero_front_wing_angle_deg: f64,
    pub aero_rear_wing_angle_deg: f64,
    pub aero_front_wing_cl: f64,
    pub aero_rear_wing_cl: f64,
    pub aero_floor_height_factor: f64,
    pub aero_floor_rake_factor: f64,
    pub aero_floor_seal_factor: f64,
    pub aero_diffuser_stall_factor: f64,
    pub aero_global_limit_factor: f64,
    pub aero_load_ratio: f64,
    pub aero_balance_front: f64,
    pub audio: AudioReadouts,
    pub modules: Vec<ModuleOutput>,
}

impl Default for CoreFrame {
    fn default() -> Self {
        Self {
            time_ms: 0,
            force: [0.0; 3],
            torque: [0.0; 3],
            speed_kmh: 0.0,
            rpm: 0.0,
            gear: 0,
            steer: 0.0,
            throttle: 0.0,
            lat_g: 0.0,
            long_g: 0.0,
            vert_g: 0.0,
            fl_comp_mm: 0.0,
            fr_comp_mm: 0.0,
            rl_comp_mm: 0.0,
            rr_comp_mm: 0.0,
            front_slip: 0.0,
            rear_slip: 0.0,
            wheel_slip_ratio: [0.0; 4],
            wheel_slip_angle_rad: [0.0; 4],
            wheel_contact_fraction: [0.0; 4],
            wheel_normal_force_n: [0.0; 4],
            tc_enabled: false,
            tc_eligible: false,
            tc_active: false,
            tc_gear_authority: 0.0,
            tc_slip_target: 0.0,
            tc_raw_cut_ratio: 0.0,
            tc_cut_ratio: 0.0,
            tc_slip_ratio: [0.0; 4],
            wheel_drive_torque_pre_tc_nm: [0.0; 4],
            wheel_drive_torque_nm: [0.0; 4],
            drive_torque: 0.0,
            pre_tc_drive_power_w: 0.0,
            net_drive_power_w: 0.0,
            px: 0.0,
            py: 0.0,
            pz: 0.0,
            yaw: 0.0,
            lvx: 0.0,
            lvy: 0.0,
            lvz: 0.0,
            avx: 0.0,
            avy: 0.0,
            avz: 0.0,
            tire_pressure_kpa: [0.0; 4],
            tire_tread_inner_c: [0.0; 4],
            tire_tread_center_c: [0.0; 4],
            tire_tread_outer_c: [0.0; 4],
            tire_carcass_c: [0.0; 4],
            tire_gas_c: [0.0; 4],
            brake_disc_c: [0.0; 4],
            brake_rim_c: [0.0; 4],
            brake_efficiency: [0.0; 4],
            duct_mass_flow_kg_s: [0.0; 4],
            duct_drag_n: [0.0; 4],
            total_brake_duct_drag_n: 0.0,
            brake_optimal_min_c: 0.0,
            brake_optimal_max_c: 0.0,
            brake_fade_start_c: 0.0,
            brake_critical_c: 0.0,
            brake_torque_nm: [0.0; 4],
            brake_spin_pre_rad_s: [0.0; 4],
            brake_spin_post_rad_s: [0.0; 4],
            brake_power_w: [0.0; 4],
            brake_energy_j: [0.0; 4],
            brake_natural_cooling_w_k: [0.0; 4],
            brake_speed_cooling_w_k: [0.0; 4],
            underfloor_clearance_m: [0.35; 5],
            underfloor_valid_mask: 0,
            underfloor_scrape_phase: 0,
            underfloor_min_clearance_m: 0.35,
            underfloor_rake_rad: 0.0,
            underfloor_roll_rad: 0.0,
            underfloor_contact_confidence: 0.0,
            underfloor_scrape_intensity: 0.0,
            underfloor_compression_m: [0.0; 5],
            underfloor_closing_speed_m_s: [0.0; 5],
            underfloor_normal_force_n: [0.0; 5],
            underfloor_bottoming_phase: [0; 5],
            underfloor_active_probe_mask: 0,
            underfloor_total_normal_force_n: 0.0,
            underfloor_max_probe_force_n: 0.0,
            underfloor_force_center_local: [0.0; 3],
            underfloor_bottoming_torque: [0.0; 3],
            underfloor_dissipated_energy_j: 0.0,
            underfloor_rigid_contact_blend: 0.0,
            aero_total_downforce_n: 0.0,
            aero_raw_downforce_n: 0.0,
            aero_front_downforce_n: 0.0,
            aero_floor_downforce_n: 0.0,
            aero_rear_downforce_n: 0.0,
            aero_drag_n: 0.0,
            aero_front_wing_angle_deg: 0.0,
            aero_rear_wing_angle_deg: 0.0,
            aero_front_wing_cl: 0.0,
            aero_rear_wing_cl: 0.0,
            aero_floor_height_factor: 0.0,
            aero_floor_rake_factor: 0.0,
            aero_floor_seal_factor: 0.0,
            aero_diffuser_stall_factor: 0.0,
            aero_global_limit_factor: 1.0,
            aero_load_ratio: 0.0,
            aero_balance_front: 0.0,
            audio: AudioReadouts::default(),
            modules: Vec::new(),
        }
    }
}
