//! SUS-GEO-07: validated pose tables unifying physics and visuals.
//!
//! The Rust solver stays the authority for forces. Godot renders from the
//! SAME validated data: per-corner tables generated by [`generate_table`]
//! from the physical geometry (hub, upright basis, rocker, damper, linkage
//! camber/toe over the reachable travel x rack envelope). The GDScript side
//! (`game/scripts/vehicle/suspension_table.gd`, same schema + bilinear math)
//! interpolates instead of running its own PBD/clamps, so physics and visuals
//! cannot diverge. Envelope clamping replaces the old visual travel clamp.
//!
//! Schema `geometry_table/1`: `{version, wheel, q_min, q_max, n_q, rack_min,
//! rack_max, n_rack, samples[q][rack]: {hub, upright[9], rocker, damper,
//! camber, toe}}`. Bilinear in (q, rack), clamped to bounds.

use crate::suspension_geo_config::GeometricSuspensionConfig;
use crate::suspension_kinematics::solve_corner;
use crate::types::{Mat3, Vec3, WheelIndex};
use serde::{Deserialize, Serialize};

pub const TABLE_VERSION: u32 = 1;
/// Max interpolation error vs the direct solve accepted by parity tests
/// (33x9 nodes; sub-mm hub, mrad attitude: invisible and physically inert).
pub const TABLE_PARITY_HUB_M: f64 = 1e-3;
pub const TABLE_PARITY_ANGLE_RAD: f64 = 4e-3;

#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct TableSample {
    pub hub: Vec3,
    pub upright: Mat3,
    pub rocker_angle: f64,
    pub damper_length: f64,
    pub camber_link: f64,
    pub toe_link: f64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CornerTable {
    pub version: u32,
    pub wheel: WheelIndex,
    pub q_min: f64,
    pub q_max: f64,
    pub n_q: usize,
    pub rack_min: f64,
    pub rack_max: f64,
    pub n_rack: usize,
    /// Row-major samples[q][rack].
    pub samples: Vec<TableSample>,
}

impl CornerTable {
    fn idx(&self, iq: usize, ir: usize) -> &TableSample {
        &self.samples[iq * self.n_rack + ir]
    }

    fn grid_pos(&self, q: f64, rack: f64) -> (f64, f64) {
        let fq = if self.n_q < 2 || !(self.q_max > self.q_min) {
            0.0
        } else {
            ((q.clamp(self.q_min, self.q_max) - self.q_min) / (self.q_max - self.q_min))
                * (self.n_q - 1) as f64
        };
        let fr = if self.n_rack < 2 || !(self.rack_max > self.rack_min) {
            0.0
        } else {
            ((rack.clamp(self.rack_min, self.rack_max) - self.rack_min)
                / (self.rack_max - self.rack_min))
                * (self.n_rack - 1) as f64
        };
        (fq, fr)
    }

    /// Bilinear sample, clamped to the validated envelope (replaces visual
    /// travel clamps). Mirrored line-by-line in suspension_table.gd.
    pub fn sample(&self, q: f64, rack: f64) -> TableSample {
        let (fq, fr) = self.grid_pos(
            if q.is_finite() { q } else { 0.0 },
            if rack.is_finite() { rack } else { 0.0 },
        );
        let q0 = (fq.floor() as usize).min(self.n_q - 1);
        let q1 = (q0 + 1).min(self.n_q - 1);
        let r0 = (fr.floor() as usize).min(self.n_rack - 1);
        let r1 = (r0 + 1).min(self.n_rack - 1);
        let tq = fq - q0 as f64;
        let tr = fr - r0 as f64;
        let a = self.idx(q0, r0);
        let b = self.idx(q1, r0);
        let c = self.idx(q0, r1);
        let d = self.idx(q1, r1);
        let lerp = |x0: f64, x1: f64| x0 + (x1 - x0) * tq;
        let hub = Vec3::new(
            lerp(a.hub.x, b.hub.x) + (lerp(c.hub.x, d.hub.x) - lerp(a.hub.x, b.hub.x)) * tr,
            lerp(a.hub.y, b.hub.y) + (lerp(c.hub.y, d.hub.y) - lerp(a.hub.y, b.hub.y)) * tr,
            lerp(a.hub.z, b.hub.z) + (lerp(c.hub.z, d.hub.z) - lerp(a.hub.z, b.hub.z)) * tr,
        );
        // Basis lerp + re-orthonormalize (small angles between nodes).
        let bx = Vec3::new(
            lerp(a.upright.x.x, b.upright.x.x)
                + (lerp(c.upright.x.x, d.upright.x.x) - lerp(a.upright.x.x, b.upright.x.x)) * tr,
            lerp(a.upright.x.y, b.upright.x.y)
                + (lerp(c.upright.x.y, d.upright.x.y) - lerp(a.upright.x.y, b.upright.x.y)) * tr,
            lerp(a.upright.x.z, b.upright.x.z)
                + (lerp(c.upright.x.z, d.upright.x.z) - lerp(a.upright.x.z, b.upright.x.z)) * tr,
        );
        let by = Vec3::new(
            lerp(a.upright.y.x, b.upright.y.x)
                + (lerp(c.upright.y.y, d.upright.y.y) - lerp(a.upright.y.y, b.upright.y.y)) * tr,
            lerp(a.upright.y.y, b.upright.y.y)
                + (lerp(c.upright.y.y, d.upright.y.y) - lerp(a.upright.y.y, b.upright.y.y)) * tr,
            lerp(a.upright.y.z, b.upright.y.z)
                + (lerp(c.upright.y.z, d.upright.y.z) - lerp(a.upright.y.z, b.upright.y.z)) * tr,
        );
        let upright = orthonormalize_cols(bx, by);
        TableSample {
            hub,
            upright,
            rocker_angle: lerp(a.rocker_angle, b.rocker_angle)
                + (lerp(c.rocker_angle, d.rocker_angle) - lerp(a.rocker_angle, b.rocker_angle)) * tr,
            damper_length: lerp(a.damper_length, b.damper_length)
                + (lerp(c.damper_length, d.damper_length) - lerp(a.damper_length, b.damper_length))
                    * tr,
            camber_link: lerp(a.camber_link, b.camber_link)
                + (lerp(c.camber_link, d.camber_link) - lerp(a.camber_link, b.camber_link)) * tr,
            toe_link: lerp(a.toe_link, b.toe_link)
                + (lerp(c.toe_link, d.toe_link) - lerp(a.toe_link, b.toe_link)) * tr,
        }
    }

    pub fn to_json_value(&self) -> serde_json::Value {
        serde_json::to_value(self).expect("table serializes")
    }

    pub fn from_json_value(v: &serde_json::Value) -> Result<Self, String> {
        let t: Self =
            serde_json::from_value(v.clone()).map_err(|e| format!("geometry_table: {e}"))?;
        if t.version != TABLE_VERSION {
            return Err(format!(
                "geometry_table.version must be {} (got {})",
                TABLE_VERSION, t.version
            ));
        }
        if t.samples.len() != t.n_q * t.n_rack || t.n_q < 2 || t.n_rack < 1 {
            return Err("geometry_table: sample count mismatch".to_string());
        }
        Ok(t)
    }
}

fn orthonormalize_cols(bx: Vec3, by: Vec3) -> Mat3 {
    let mut x = if bx.length_squared() > 1e-12 {
        bx.normalized()
    } else {
        Vec3::RIGHT
    };
    let mut y = by - x * (by.dot(x));
    if y.length_squared() < 1e-12 {
        y = Vec3::UP - x * (Vec3::UP.dot(x));
        if y.length_squared() < 1e-12 {
            y = Vec3::FORWARD;
        }
    }
    y = y.normalized();
    let z = x.cross(y).normalized();
    x = y.cross(z).normalized();
    Mat3::from_cols(x, y, z)
}

/// Generate a validated table for one wheel: sweep the reachable envelope
/// (SUS-GEO-03) x rack range. Rear corners ignore rack (n_rack = 1).
pub fn generate_table(
    geo: &GeometricSuspensionConfig,
    wheel: WheelIndex,
    n_q: usize,
    n_rack: usize,
    rack_half_range_m: f64,
) -> Result<CornerTable, String> {
    let corner = geo.corners.get(wheel);
    let axle = geo.axle(wheel);
    let (lo, hi) = crate::suspension_kinematics::travel_envelope(
        corner,
        axle.wheel_droop_m,
        axle.wheel_bump_m,
        0.0,
        wheel.is_front(),
    );
    if !(hi > lo) {
        return Err(format!("{wheel:?}: empty reachable envelope"));
    }
    let n_q = n_q.clamp(2, 257);
    let (rack_min, rack_max, n_rack) = if wheel.is_front() {
        let h = if rack_half_range_m.is_finite() && rack_half_range_m > 0.0 {
            rack_half_range_m
        } else {
            0.02
        };
        (-h, h, n_rack.clamp(1, 65))
    } else {
        (0.0, 0.0, 1)
    };
    let side = if wheel.is_left() { 1.0 } else { -1.0 };
    let mut samples = Vec::with_capacity(n_q * n_rack);
    for iq in 0..n_q {
        let q = lo + (hi - lo) * (iq as f64 / (n_q - 1) as f64);
        for ir in 0..n_rack {
            let rack = if n_rack < 2 {
                0.0
            } else {
                rack_min + (rack_max - rack_min) * (ir as f64 / (n_rack - 1) as f64)
            };
            let sol = solve_corner(corner, q, rack, wheel.is_front(), 0.0, 0.0, side)
                .ok_or_else(|| format!("{wheel:?}: no solve at q={q} rack={rack}"))?;
            if !sol.converged {
                return Err(format!("{wheel:?}: unreachable node q={q} rack={rack}"));
            }
            samples.push(TableSample {
                hub: sol.hub,
                upright: sol.upright_basis,
                rocker_angle: sol.rocker_angle,
                damper_length: sol.damper_length,
                camber_link: side * sol.upright_basis.x.y.clamp(-1.0, 1.0).asin(),
                toe_link: side * sol.upright_basis.z.x.clamp(-1.0, 1.0).asin(),
            });
        }
    }
    Ok(CornerTable {
        version: TABLE_VERSION,
        wheel,
        q_min: lo,
        q_max: hi,
        n_q,
        rack_min,
        rack_max,
        n_rack,
        samples,
    })
}

/// Max hub/angle error of the table vs direct solves over a grid.
pub fn parity_error(table: &CornerTable, geo: &GeometricSuspensionConfig) -> (f64, f64) {
    let corner = geo.corners.get(table.wheel);
    let side = if table.wheel.is_left() { 1.0 } else { -1.0 };
    let mut hub_err: f64 = 0.0;
    let mut ang_err: f64 = 0.0;
    for iq in 0..=8 {
        let q = table.q_min + (table.q_max - table.q_min) * (iq as f64 / 8.0);
        // Off-node queries (mid-cell) stress the interpolation; stay inside
        // the validated envelope (outside, the table clamps by design while
        // the raw solver does not).
        let qq = (q + (table.q_max - table.q_min) * 0.06125).clamp(table.q_min, table.q_max);
        for ir in 0..=4 {
            let rack = if table.n_rack < 2 {
                0.0
            } else {
                (table.rack_min + (table.rack_max - table.rack_min) * (ir as f64 / 4.0)
                    + (table.rack_max - table.rack_min) * 0.03125)
                    .clamp(table.rack_min, table.rack_max)
            };
            let t = table.sample(qq, rack);
            if let Some(sol) = solve_corner(corner, qq, rack, table.wheel.is_front(), 0.0, 0.0, side)
            {
                if !sol.converged {
                    continue;
                }
                hub_err = hub_err.max((t.hub - sol.hub).length());
                let e = (t.upright.x - sol.upright_basis.x).length()
                    + (t.upright.y - sol.upright_basis.y).length();
                ang_err = ang_err.max(e);
            }
        }
    }
    (hub_err, ang_err)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture_geo() -> GeometricSuspensionConfig {
        // Healthy trailing-rocker geometry (same family as 05/06 fixtures).
        let json = serde_json::json!({
            "version": 1,
            "front": {
                "spring_rate_N_per_m": 117000.0, "spring_free_length_m": 0.2826,
                "spring_installed_length_m": 0.26,
                "damper_bump_Ns_per_m": 11800.0, "damper_rebound_Ns_per_m": 15930.0,
                "damper_knee_m_per_s": 0.127, "damper_fast_factor": 0.5,
                "wheel_droop_m": 0.05, "wheel_bump_m": 0.10,
                "damper_min_m": 0.15, "damper_max_m": 0.40, "bump_stop_mult": 2.6,
            },
            "rear": {
                "spring_rate_N_per_m": 185000.0, "spring_free_length_m": 0.2727,
                "spring_installed_length_m": 0.25,
                "damper_bump_Ns_per_m": 20500.0, "damper_rebound_Ns_per_m": 27675.0,
                "damper_knee_m_per_s": 0.127, "damper_fast_factor": 0.5,
                "wheel_droop_m": 0.05, "wheel_bump_m": 0.10,
                "damper_min_m": 0.15, "damper_max_m": 0.40, "bump_stop_mult": 2.8,
            },
            "front_arb": {"mode": "legacy_ratio", "ratio": 0.15},
            "rear_arb": {"mode": "legacy_ratio", "ratio": 0.09},
            "corners": {
                "FL": {
                    "hub_center": [-0.753, 0.0, -1.475],
                    "lower_wishbone": {"inner_front": [-0.165237, -0.032255, -1.520731], "inner_rear": [-0.1912, -0.031258, -1.063059], "outer": [-0.585831, -0.0317, -1.478898]},
                    "upper_wishbone": {"inner_front": [-0.165237, 0.136096, -1.520731], "inner_rear": [-0.1912, 0.137093, -1.196632], "outer": [-0.585831, 0.13665, -1.478898]},
                    "trackrod": {"inner": [-0.163643, -0.0329515, -1.6063275], "outer": [-0.581991, -0.0334055, -1.586078]},
                    "rod": {"outer": [-0.549739, -0.019274, -1.4389295], "attachment": "lower", "type": "pushrod"},
                    "rocker": {"pivot": [-0.162718, 0.2204355, -1.4462085], "axis": [1.0, 0.0, 0.0], "pushrod_arm": [-0.162718, 0.2204355, -1.6062085], "damper_arm": [-0.162718, 0.2204355, -1.5262085]},
                    "damper": {"chassis": [-0.162718, 0.5004355, -1.5462085]},
                },
                "FR": {"mirror_of": "FL"},
                "RL": {
                    "hub_center": [-0.716, 0.0, 1.475],
                    "lower_wishbone": {"inner_front": [-0.2916855, -0.1203565, 1.1482685], "inner_rear": [-0.073654, -0.1203565, 1.624112], "outer": [-0.505193, -0.0596035, 1.474073]},
                    "upper_wishbone": {"inner_front": [-0.1457255, 0.0552935, 1.1460325], "inner_rear": [-0.073654, 0.0512445, 1.624112], "outer": [-0.505193, 0.1160465, 1.474073]},
                    "trackrod": {"inner": [-0.085, -0.015, 1.61], "outer": [-0.505193, -0.015, 1.55]},
                    "rod": {"outer": [-0.48, 0.11, 1.43], "attachment": "upper", "type": "pullrod"},
                    "rocker": {"pivot": [-0.2, -0.145, 1.39], "axis": [1.0, 0.0, 0.0], "pushrod_arm": [-0.2, -0.145, 1.25], "damper_arm": [-0.2, -0.145, 1.32]},
                    "damper": {"chassis": [-0.2, 0.115, 1.34]},
                    "driveshaft": {"inner": [-0.088833, -0.0033785, 1.487802], "outer": [-0.716, 0.0, 1.475]},
                },
                "RR": {"mirror_of": "RL"},
            }
        });
        crate::suspension_geo_config::geometric_from_json_value(&json).expect("fixture")
    }

    #[test]
    fn table_parity_within_tolerance() {
        let geo = fixture_geo();
        for wheel in [WheelIndex::FrontLeft, WheelIndex::RearLeft] {
            let t = generate_table(&geo, wheel, 33, if wheel.is_front() { 9 } else { 1 }, 0.02)
                .expect("table");
            let (hub_err, ang_err) = parity_error(&t, &geo);
            assert!(hub_err < TABLE_PARITY_HUB_M, "{wheel:?} hub {hub_err}");
            assert!(ang_err < TABLE_PARITY_ANGLE_RAD, "{wheel:?} angle {ang_err}");
            // JSON round-trip preserves the table bit-for-bit.
            let v = t.to_json_value();
            let t2 = CornerTable::from_json_value(&v).expect("round-trip");
            assert_eq!(t, t2);
        }
    }

    #[test]
    fn table_clamps_to_envelope() {
        let geo = fixture_geo();
        let t = generate_table(&geo, WheelIndex::FrontLeft, 9, 3, 0.02).unwrap();
        let beyond = t.sample(t.q_max + 1.0, t.rack_max + 1.0);
        let edge = t.sample(t.q_max, t.rack_max);
        assert!((beyond.hub - edge.hub).length() < 1e-12);
        assert!((beyond.rocker_angle - edge.rocker_angle).abs() < 1e-12);
    }
}
