//! Integration tests against the real v10_vehicle bank on disk.
//!
//! These require the bank to exist (generated by tools/audio/bank_generator.py).
//! They validate: bank load/format/sha256, loop-buffer access, and that the mix
//! state produces the expected deterministic decisions for the offline scenarios.

use std::path::Path;

use vehicle_audio_engine::adapter::surface_token;
use vehicle_audio_engine::bank::VehicleSoundBank;
use vehicle_audio_engine::state::{
    engine_weights, StateInput, SURFACE_GRASS, SURFACE_RUMBLE, SURFACE_SAND,
};
use vehicle_audio_engine::VehicleAudioEngine;
use vehicle_audio_engine::VehicleAudioState;

fn bank_path() -> std::path::PathBuf {
    // Cargo sets CARGO_MANIFEST_DIR to game/crates/vehicle-audio-engine.
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    manifest_dir
        .parent()
        .unwrap()
        .parent()
        .unwrap() // game/
        .join("sounds/banks/v10_vehicle")
}

fn require_bank() -> Option<VehicleSoundBank> {
    let path = bank_path();
    if !path.join("bank_manifest.json").is_file() {
        eprintln!(
            "SKIP: bank not present at {} (run tools/audio/bank_generator.py)",
            path.display()
        );
        return None;
    }
    match VehicleSoundBank::load(&path) {
        Ok(bank) => Some(bank),
        Err(e) => {
            eprintln!("SKIP: bank load failed: {e}");
            None
        }
    }
}

#[test]
fn bank_loads_and_has_expected_entries() {
    let Some(bank) = require_bank() else { return };
    assert_eq!(bank.bank_name, "v10_vehicle");
    assert!(!bank.is_empty());
    // Kept one-shots / beds must all be present.
    for key in [
        "surf_sand",
        "surf_grass",
        "surf_rumble",
        "impact_barrier",
        "impact_cone",
        "impact_fire",
        "impact_scrape",
        "impact_hit_1",
        "impact_hit_2",
        "impact_hit_3",
        "impact_hit_4",
        "shift_up",
        "shift_down",
        "shift_3",
        "engine_starter",
        "engine_start_backfire",
        "int_backfire",
        "int_backfire_2",
        "tyre_scrub",
    ] {
        assert!(bank.get(key).is_some(), "missing bank key {key}");
    }
    // Retired continues (engine bands + exhaust mic) must be absent from the bank.
    for key in [
        "engine_idle",
        "engine_low",
        "engine_mid",
        "engine_high",
        "engine_redline",
        "engine_limiter",
        "engine_tc",
        "exhaust-mic",
    ] {
        assert!(
            bank.get(key).is_none(),
            "retired key {key} still present in bank"
        );
    }
    // One-shots vs loops.
    assert!(!bank.get("impact_barrier").unwrap().is_loop);
    assert!(bank.get("surf_grass").unwrap().is_loop);
    assert!(bank.get("tyre_scrub").unwrap().is_loop);
    // Sampled engine bands are retired: the bank exposes an empty band set and the
    // engine is now driven by the procedural synth.
    assert!(bank.engine_bands.is_empty());
    assert_eq!(bank.native_rpm("exhaust-mic"), None);
    assert_eq!(
        bank.retired_names,
        [
            "engine_high",
            "engine_idle",
            "engine_limiter",
            "engine_low",
            "engine_mid",
            "engine_redline",
            "engine_tc",
            "exhaust-mic",
        ]
        .map(String::from)
        .to_vec()
    );
}

#[test]
fn tyre_scrub_voice_activates_and_advances_on_loaded_bank() {
    let mut engine = VehicleAudioEngine::new(&bank_path()).expect("canonical bank must load");
    engine.set_state(9000.0, 4500.0, 17000.0, 0.5, 100.0, 3, 0.4, "asphalt");
    engine.set_tire_scrub_state([0.45; 4], [0.0; 4], [1.0; 4], [3500.0; 4], 100.0, "asphalt");
    let mut left = vec![0.0; 4096];
    let mut right = vec![0.0; 4096];
    engine.render(&mut left, &mut right, 4096);
    assert!(engine.tyre_scrub_gain() > 0.5);
    assert!(engine.tyre_scrub_cursor() > 0.0);
    assert_eq!(engine.tyre_scrub_mode(), 2);
}

#[test]
fn bank_samples_are_mono_44k_and_reasonable_duration() {
    let Some(bank) = require_bank() else { return };
    for (key, sample) in bank.samples.iter() {
        assert_eq!(sample.sample_rate, 44100, "{key} sample rate");
        assert!(!sample.pcm.is_empty(), "{key} empty");
        assert!(sample.duration_s() > 0.1, "{key} too short");
    }
}

#[test]
fn loop_sample_stays_in_range_across_wrap() {
    let Some(bank) = require_bank() else { return };
    let engine = bank.get("surf_grass").unwrap();
    // Wrap across several loop iterations; every read must be finite and in [-1,1].
    for step in (0..engine.pcm.len() * 3 + 100).step_by(997) {
        let v = vehicle_audio_engine::dsp::loop_sample(&engine.pcm, step);
        assert!(
            v.is_finite() && (-1.0..=1.0).contains(&v),
            "step {step} -> {v}"
        );
    }
}

#[allow(clippy::too_many_arguments)]
fn state(
    rpm: f64,
    idle: f64,
    max: f64,
    throttle: f32,
    speed: f64,
    gear: i32,
    slip: f32,
    surface: &'static str,
) -> VehicleAudioState {
    VehicleAudioState::from_input(&StateInput {
        rpm,
        idle_rpm: idle,
        max_rpm: max,
        throttle,
        speed_kph: speed,
        gear,
        slip,
        surface,
    })
}

#[test]
fn offline_scenario_states_produce_expected_mix_decisions() {
    let Some(bank) = require_bank() else { return };
    let bands = &bank.engine_bands;
    // Sampled engine bands are retired, so the loaded bank has an empty band set:
    // the engine crossfade degrades to the deterministic band-0 fallback, while the
    // surface-bed, gain and trigger decisions remain meaningful and must survive.
    let idle = state(2200.0, 1000.0, 15000.0, 0.15, 0.0, 1, 0.0, "asphalt");
    let m = idle.mix(bands);
    assert_eq!(m.surface_key, None);
    assert_eq!(
        m.engine_weights[0], 1.0,
        "empty-band set falls back to band 0"
    );

    let redline = state(14500.0, 1000.0, 15000.0, 1.0, 195.0, 4, 0.03, "asphalt");
    let m = redline.mix(bands);
    assert_eq!(m.surface_key, None);
    assert_eq!(
        m.engine_weights[0], 1.0,
        "empty-band set falls back to band 0"
    );
    assert!((m.engine_gain - 1.0).abs() < 1e-5);

    // Sand off-track with slip boosts the bed gain.
    let sand = state(7200.0, 1000.0, 15000.0, 0.65, 66.0, 3, 0.14, SURFACE_SAND);
    assert_eq!(sand.mix(bands).surface_key, Some("surf_sand"));
    assert!(sand.mix(bands).surface_gain > 0.0);

    // Rumble (kerb) and grass are valid beds too.
    assert_eq!(
        state(7500.0, 1000.0, 15000.0, 0.7, 75.0, 3, 0.05, SURFACE_RUMBLE)
            .mix(bands)
            .surface_key,
        Some("surf_rumble")
    );
    assert_eq!(
        state(6800.0, 1000.0, 15000.0, 0.9, 50.0, 2, 0.45, SURFACE_GRASS)
            .mix(bands)
            .surface_key,
        Some("surf_grass")
    );
}

#[test]
fn surface_token_mapping_used_by_scenarios() {
    assert_eq!(surface_token("asphalt"), "asphalt");
    assert_eq!(surface_token("sand"), "sand");
    assert_eq!(surface_token("grass"), "grass");
    assert_eq!(surface_token("rumble"), "rumble");
}

#[test]
fn weights_are_stable_golden_values() {
    let Some(bank) = require_bank() else { return };
    // Sampled engine bands are retired: the loaded bank exposes an empty band set,
    // so the crossfade degrades to the documented engine_weights fallback.
    assert!(bank.engine_bands.is_empty());
    assert_eq!(engine_weights(0.0, &bank.engine_bands)[0], 1.0);
    let weights = engine_weights(0.5, &bank.engine_bands);
    // Empty band set falls back to band 0 only; neighbours are zero.
    assert_eq!(weights[0], 1.0);
    assert!(weights[1..].iter().all(|w| *w == 0.0));
    let sum: f32 = weights.iter().sum();
    assert!((sum - 1.0).abs() < 1e-5);
}
