//! Integration tests against the real v10_vehicle bank on disk.
//!
//! These require the bank to exist (generated by tools/audio/bank_generator.py).
//! They validate: bank load/format/sha256, loop-buffer access, and that the mix
//! state produces the expected deterministic decisions for the offline scenarios.

use std::path::Path;

use vehicle_audio_engine::adapter::surface_token;
use vehicle_audio_engine::bank::VehicleSoundBank;
use vehicle_audio_engine::state::{
    engine_weights, StateInput, SURFACE_GRASS, SURFACE_RUMBLE, SURFACE_SAND,
};
use vehicle_audio_engine::VehicleAudioState;

fn bank_path() -> std::path::PathBuf {
    // Cargo sets CARGO_MANIFEST_DIR to game/crates/vehicle-audio-engine.
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    manifest_dir
        .parent()
        .unwrap()
        .parent()
        .unwrap() // game/crates/
        .parent()
        .unwrap() // game/
        .join("sounds/banks/v10_vehicle")
}

fn require_bank() -> Option<VehicleSoundBank> {
    let path = bank_path();
    if !path.join("bank_manifest.json").is_file() {
        eprintln!(
            "SKIP: bank not present at {} (run tools/audio/bank_generator.py)",
            path.display()
        );
        return None;
    }
    match VehicleSoundBank::load(&path) {
        Ok(bank) => Some(bank),
        Err(e) => {
            eprintln!("SKIP: bank load failed: {e}");
            None
        }
    }
}

#[test]
fn bank_loads_and_has_expected_entries() {
    let Some(bank) = require_bank() else { return };
    assert_eq!(bank.bank_name, "v10_vehicle");
    assert!(!bank.is_empty());
    for key in [
        "engine_idle",
        "engine_mid",
        "engine_redline",
        "surf_sand",
        "surf_grass",
        "surf_rumble",
        "impact_barrier",
        "impact_cone",
        "shift_up",
        "engine_start_backfire",
        "int_backfire",
        "int_backfire_2",
        "exhaust-mic",
        "impact_scrape",
    ] {
        assert!(bank.get(key).is_some(), "missing bank key {key}");
    }
    // Engine loops flagged as loops.
    assert!(bank.get("engine_idle").unwrap().is_loop);
    // One-shots not flagged.
    assert!(!bank.get("impact_barrier").unwrap().is_loop);
}

#[test]
fn bank_samples_are_mono_44k_and_reasonable_duration() {
    let Some(bank) = require_bank() else { return };
    for (key, sample) in bank.samples.iter() {
        assert_eq!(sample.sample_rate, 44100, "{key} sample rate");
        assert!(!sample.pcm.is_empty(), "{key} empty");
        assert!(sample.duration_s() > 0.1, "{key} too short");
    }
}

#[test]
fn loop_sample_stays_in_range_across_wrap() {
    let Some(bank) = require_bank() else { return };
    let engine = bank.get("engine_mid").unwrap();
    // Wrap across several loop iterations; every read must be finite and in [-1,1].
    for step in (0..engine.pcm.len() * 3 + 100).step_by(997) {
        let v = vehicle_audio_engine::dsp::loop_sample(&engine.pcm, step);
        assert!(
            v.is_finite() && (-1.0..=1.0).contains(&v),
            "step {step} -> {v}"
        );
    }
}

#[allow(clippy::too_many_arguments)]
fn state(
    rpm: f64,
    idle: f64,
    max: f64,
    throttle: f32,
    speed: f64,
    gear: i32,
    slip: f32,
    surface: &'static str,
) -> VehicleAudioState {
    VehicleAudioState::from_input(&StateInput {
        rpm,
        idle_rpm: idle,
        max_rpm: max,
        throttle,
        speed_kph: speed,
        gear,
        slip,
        surface,
    })
}

#[test]
fn offline_scenario_states_produce_expected_mix_decisions() {
    // Mirrors the offline renderer scenarios (asphalt/sand/grass/rumble).
    // engine mix must follow normalized rpm; asphalt has no bed.
    let idle = state(2200.0, 1000.0, 15000.0, 0.15, 0.0, 1, 0.0, "asphalt");
    let m = idle.mix();
    assert_eq!(m.surface_key, None);
    assert!(
        m.engine_weights[0] > m.engine_weights[4],
        "idle should favor idle band"
    );

    let redline = state(14500.0, 1000.0, 15000.0, 1.0, 195.0, 4, 0.03, "asphalt");
    let m = redline.mix();
    assert_eq!(m.surface_key, None);
    assert!(
        m.engine_weights[4] > m.engine_weights[0],
        "redline should favor redline band"
    );
    assert!((m.engine_gain - 1.0).abs() < 1e-5);

    // Sand off-track with slip boosts the bed gain.
    let sand = state(7200.0, 1000.0, 15000.0, 0.65, 66.0, 3, 0.14, SURFACE_SAND);
    assert_eq!(sand.mix().surface_key, Some("surf_sand"));
    assert!(sand.mix().surface_gain > 0.0);

    // Rumble (kerb) and grass are valid beds too.
    assert_eq!(
        state(7500.0, 1000.0, 15000.0, 0.7, 75.0, 3, 0.05, SURFACE_RUMBLE)
            .mix()
            .surface_key,
        Some("surf_rumble")
    );
    assert_eq!(
        state(6800.0, 1000.0, 15000.0, 0.9, 50.0, 2, 0.45, SURFACE_GRASS)
            .mix()
            .surface_key,
        Some("surf_grass")
    );
}

#[test]
fn surface_token_mapping_used_by_scenarios() {
    assert_eq!(surface_token("asphalt"), "asphalt");
    assert_eq!(surface_token("sand"), "sand");
    assert_eq!(surface_token("grass"), "grass");
    assert_eq!(surface_token("rumble"), "rumble");
}

#[test]
fn weights_are_stable_golden_values() {
    // Guard against silent regression in the crossfade curve.
    assert_eq!(engine_weights(0.0)[0], 1.0);
    let mid = engine_weights(0.5);
    // At the mid point the middle band dominates and neighbors are nonzero.
    assert!(mid[2] > mid[0] && mid[2] > mid[4]);
    let sum: f32 = mid.iter().sum();
    assert!((sum - 1.0).abs() < 1e-5);
}
