vehicle_id: v10
allow_horizontal_mirror: false
required_directions: 16
missing_frame_policy: error
frame_order: rear,rear_right_1,rear_right_2,rear_right_3,right,front_right_3,front_right_2,front_right_1,front,front_left_1,front_left_2,front_left_3,left,rear_left_3,rear_left_2,rear_left_1
angle_rear: 0
angle_rear_right_1: 22.5
angle_rear_right_2: 45
angle_rear_right_3: 67.5
angle_right: 90
angle_front_right_3: 112.5
angle_front_right_2: 135
angle_front_right_1: 157.5
angle_front: 180
angle_front_left_1: 202.5
angle_front_left_2: 225
angle_front_left_3: 247.5
angle_left: 270
angle_rear_left_3: 292.5
angle_rear_left_2: 315
angle_rear_left_1: 337.5
