#define STB_IMAGE_IMPLEMENTATION
#define STB_IMAGE_WRITE_IMPLEMENTATION
#include "formula90s_tools/sprite_toolkit.hpp"
#include "stb_image.h"
#include "stb_image_write.h"
#include <algorithm>
#include <array>
#include <cmath>
#include <cstring>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <queue>
#include <sstream>
#include <stdexcept>

namespace fs=std::filesystem;
namespace formula90s_tools {
namespace {
std::string lower(std::string value){std::transform(value.begin(),value.end(),value.begin(),[](unsigned char c){return static_cast<char>(std::tolower(c));});return value;}
int color_distance(const std::uint8_t *p,const std::array<std::uint8_t,3>&c){int dr=int(p[0])-c[0],dg=int(p[1])-c[1],db=int(p[2])-c[2];return static_cast<int>(std::sqrt(double(dr*dr+dg*dg+db*db)));}
std::array<std::uint8_t,3> corner_color(const Image &im){std::array<unsigned,3> sum{};const int points[4][2]={{0,0},{im.width-1,0},{0,im.height-1},{im.width-1,im.height-1}};for(auto&p:points){const auto*q=im.pixel(p[0],p[1]);for(int c=0;c<3;c++)sum[c]+=q[c];}return {std::uint8_t(sum[0]/4),std::uint8_t(sum[1]/4),std::uint8_t(sum[2]/4)};}
std::string json_escape(const std::string &s){std::string out;for(char c:s){if(c=='\\'||c=='"')out+='\\';out+=c;}return out;}
class Sha256 { std::uint32_t h[8]={0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19};std::vector<std::uint8_t>b;std::uint64_t bits=0;static std::uint32_t r(std::uint32_t x,int n){return(x>>n)|(x<<(32-n));}void block(const std::uint8_t*p){static const std::uint32_t k[64]={0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2};std::uint32_t w[64];for(int i=0;i<16;i++)w[i]=(std::uint32_t(p[i*4])<<24)|(std::uint32_t(p[i*4+1])<<16)|(std::uint32_t(p[i*4+2])<<8)|p[i*4+3];for(int i=16;i<64;i++){auto s0=r(w[i-15],7)^r(w[i-15],18)^(w[i-15]>>3);auto s1=r(w[i-2],17)^r(w[i-2],19)^(w[i-2]>>10);w[i]=w[i-16]+s0+w[i-7]+s1;}auto a=h[0],c=h[2],d=h[3],e=h[4],f=h[5],g=h[6],hh=h[7],bb=h[1];for(int i=0;i<64;i++){auto s1=r(e,6)^r(e,11)^r(e,25);auto ch=(e&f)^((~e)&g);auto t1=hh+s1+ch+k[i]+w[i];auto s0=r(a,2)^r(a,13)^r(a,22);auto maj=(a&bb)^(a&c)^(bb&c);auto t2=s0+maj;hh=g;g=f;f=e;e=d+t1;d=c;c=bb;bb=a;a=t1+t2;}h[0]+=a;h[1]+=bb;h[2]+=c;h[3]+=d;h[4]+=e;h[5]+=f;h[6]+=g;h[7]+=hh;}public:void add(const std::uint8_t*p,std::size_t n){bits+=n*8;b.insert(b.end(),p,p+n);while(b.size()>=64){block(b.data());b.erase(b.begin(),b.begin()+64);}}std::string finish(){b.push_back(0x80);while((b.size()%64)!=56)b.push_back(0);for(int i=7;i>=0;i--)b.push_back(std::uint8_t(bits>>(i*8)));while(!b.empty()){block(b.data());b.erase(b.begin(),b.begin()+64);}std::ostringstream o;o<<std::hex<<std::setfill('0');for(auto v:h)o<<std::setw(8)<<v;return o.str();}};
}
Image load_image(const fs::path &path){if(!fs::exists(path))throw std::runtime_error("input does not exist: "+path.string());auto ext=lower(path.extension().string());if(ext!=".png"&&ext!=".jpg"&&ext!=".jpeg")throw std::runtime_error(ext==".webp"?"WEBP is not supported by the stb build":"unsupported image format: "+ext);int w=0,h=0,c=0;stbi_uc*p=stbi_load(path.string().c_str(),&w,&h,&c,4);if(!p)throw std::runtime_error(std::string("corrupt or unreadable image: ")+stbi_failure_reason());if(w<=0||h<=0||w>16384||h>16384||std::uint64_t(w)*h>100000000){stbi_image_free(p);throw std::runtime_error("invalid or excessive image dimensions");}Image out{w,h,std::vector<std::uint8_t>(p,p+std::size_t(w)*h*4)};stbi_image_free(p);return out;}
void write_png(const fs::path &path,const Image &im,bool force){if(!im.valid())throw std::runtime_error("cannot write invalid image");if(fs::exists(path)&&!force)throw std::runtime_error("output exists; pass --force: "+path.string());fs::create_directories(path.parent_path());if(!stbi_write_png(path.string().c_str(),im.width,im.height,4,im.rgba.data(),im.width*4))throw std::runtime_error("failed to write PNG: "+path.string());}
std::string sha256_file(const fs::path&p){std::ifstream f(p,std::ios::binary);if(!f)throw std::runtime_error("cannot hash file");Sha256 s;std::array<std::uint8_t,65536>b{};while(f){f.read(reinterpret_cast<char*>(b.data()),b.size());s.add(b.data(),static_cast<std::size_t>(f.gcount()));}return s.finish();}
std::array<std::uint8_t,3> parse_hex_color(const std::string &v){if(v.size()!=7||v[0]!='#')throw std::runtime_error("background color must be #RRGGBB");return {std::uint8_t(std::stoul(v.substr(1,2),nullptr,16)),std::uint8_t(std::stoul(v.substr(3,2),nullptr,16)),std::uint8_t(std::stoul(v.substr(5,2),nullptr,16))};}
double remove_background(Image&im,const std::string&mode,int tolerance,int softness,const std::array<std::uint8_t,3>&manual){if(mode=="preserve")return 0;if(mode!="corners"&&mode!="color")throw std::runtime_error("background mode must be preserve, corners or color");auto key=mode=="corners"?corner_color(im):manual;std::size_t removed=0;int feather=std::max(0,softness)*8;for(int y=0;y<im.height;y++)for(int x=0;x<im.width;x++){auto*p=im.pixel(x,y);int dist=color_distance(p,key);if(dist<=tolerance){p[0]=p[1]=p[2]=p[3]=0;removed++;}else if(feather>0&&dist<tolerance+feather){p[3]=std::uint8_t(255.0*(dist-tolerance)/feather);removed++;}}double ratio=double(removed)/(im.width*im.height);if(ratio>0.995)throw std::runtime_error("background mask would remove the entire image");return ratio;}
Rect alpha_bounds(const Image&im,std::uint8_t t){int minx=im.width,miny=im.height,maxx=-1,maxy=-1;for(int y=0;y<im.height;y++)for(int x=0;x<im.width;x++)if(im.pixel(x,y)[3]>t){minx=std::min(minx,x);miny=std::min(miny,y);maxx=std::max(maxx,x);maxy=std::max(maxy,y);}return maxx<minx?Rect{}:Rect{minx,miny,maxx-minx+1,maxy-miny+1};}
Image crop_image(const Image&im,const Rect&r){if(!r.valid()||r.x<0||r.y<0||r.x+r.width>im.width||r.y+r.height>im.height)throw std::runtime_error("invalid crop rectangle");Image out{r.width,r.height,std::vector<std::uint8_t>(std::size_t(r.width)*r.height*4)};for(int y=0;y<r.height;y++)std::memcpy(out.pixel(0,y),im.pixel(r.x,r.y+y),std::size_t(r.width)*4);return out;}
Image resize_nearest(const Image&im,int w,int h){if(w<=0||h<=0)throw std::runtime_error("invalid resize dimensions");Image out{w,h,std::vector<std::uint8_t>(std::size_t(w)*h*4)};for(int y=0;y<h;y++)for(int x=0;x<w;x++)std::memcpy(out.pixel(x,y),im.pixel(std::min(im.width-1,x*im.width/w),std::min(im.height-1,y*im.height/h)),4);return out;}
Image align_on_canvas(const Image&im,int w,int h,int ox,int oy){if(im.width>w||im.height>h)throw std::runtime_error("content exceeds canvas");Image out{w,h,std::vector<std::uint8_t>(std::size_t(w)*h*4,0)};int dx=(w-im.width)/2+ox,dy=h-im.height+oy;if(dx<0||dy<0||dx+im.width>w||dy+im.height>h)throw std::runtime_error("alignment offset exceeds canvas");for(int y=0;y<im.height;y++)std::memcpy(out.pixel(dx,dy+y),im.pixel(0,y),std::size_t(im.width)*4);return out;}
PrepareResult prepare_sprite(const PrepareOptions&o){Image original=load_image(o.input);Rect source=o.source_crop.valid()?o.source_crop:Rect{0,0,original.width,original.height};Image work=crop_image(original,source);double removed=remove_background(work,o.background_mode,o.tolerance,o.edge_softness,o.background_color);Rect bounds=alpha_bounds(work);if(!bounds.valid())throw std::runtime_error("image has no visible content");if(o.crop){bounds.x=std::max(0,bounds.x-o.padding);bounds.y=std::max(0,bounds.y-o.padding);bounds.width=std::min(work.width-bounds.x,bounds.width+o.padding*2);bounds.height=std::min(work.height-bounds.y,bounds.height+o.padding*2);work=crop_image(work,bounds);}double scale=std::min(double(o.canvas_width-2*o.padding)/work.width,double(o.canvas_height-2*o.padding)/work.height);if(scale<=0)throw std::runtime_error("canvas too small");if(scale>4.0)std::cerr<<"WARNING: enlargement exceeds 4x\n";int rw=std::max(1,int(std::round(work.width*scale))),rh=std::max(1,int(std::round(work.height*scale)));Image result=align_on_canvas(resize_nearest(work,rw,rh),o.canvas_width,o.canvas_height);return {std::move(result),source,bounds,sha256_file(o.input),removed};}
std::map<std::string,std::string> parse_args(int argc,char**argv){std::map<std::string,std::string>m;for(int i=1;i<argc;i++){std::string k=argv[i];if(k.rfind("--",0)!=0)throw std::runtime_error("unexpected argument: "+k);k=k.substr(2);if(k=="force"||k=="dry-run"||k=="no-crop")m[k]="true";else{if(++i>=argc)throw std::runtime_error("missing value for --"+k);m[k]=argv[i];}}return m;}
std::map<std::string,std::string> read_simple_config(const fs::path&p){std::map<std::string,std::string>m;if(p.empty())return m;std::ifstream f(p);if(!f)throw std::runtime_error("cannot read config: "+p.string());std::string line;while(std::getline(f,line)){auto hash=line.find('#');if(hash!=std::string::npos)line.resize(hash);auto colon=line.find(':');if(colon==std::string::npos)continue;auto k=line.substr(0,colon),v=line.substr(colon+1);auto trim=[](std::string&s){auto a=s.find_first_not_of(" \t\r\n\"");auto b=s.find_last_not_of(" \t\r\n\"");s=a==std::string::npos?"":s.substr(a,b-a+1);};trim(k);trim(v);if(!k.empty())m[k]=v;}return m;}
void write_prepare_metadata(const PrepareOptions&o,const PrepareResult&r){if(fs::exists(o.metadata)&&!o.force)throw std::runtime_error("metadata exists; pass --force");fs::create_directories(o.metadata.parent_path());std::ofstream f(o.metadata);if(!f)throw std::runtime_error("cannot write metadata");f<<"{\n  \"schema_version\": 1,\n  \"tool_version\": \"prepare_sprite 1.0\",\n  \"vehicle_id\": \""<<json_escape(o.vehicle_id)<<"\",\n  \"vehicle_name\": \"V10\",\n  \"source\": {\"path\": \""<<json_escape(o.input.generic_string())<<"\", \"sha256\": \""<<r.source_sha256<<"\"},\n  \"original_size\": {\"width\": "<<load_image(o.input).width<<", \"height\": "<<load_image(o.input).height<<"},\n  \"source_crop\": {\"x\": "<<r.source_bounds.x<<", \"y\": "<<r.source_bounds.y<<", \"width\": "<<r.source_bounds.width<<", \"height\": "<<r.source_bounds.height<<"},\n  \"content_bounds\": {\"x\": "<<r.content_bounds.x<<", \"y\": "<<r.content_bounds.y<<", \"width\": "<<r.content_bounds.width<<", \"height\": "<<r.content_bounds.height<<"},\n  \"output_size\": {\"width\": "<<r.image.width<<", \"height\": "<<r.image.height<<"},\n  \"anchor\": {\"x\": 0.5, \"y\": 1.0},\n  \"offset\": {\"x\": 0, \"y\": 0},\n  \"orientation\": \""<<json_escape(o.orientation)<<"\",\n  \"scale\": 0.018,\n  \"background_removal\": {\"mode\": \""<<o.background_mode<<"\", \"tolerance\": "<<o.tolerance<<", \"removed_ratio\": "<<r.removed_ratio<<"},\n  \"palette_mode\": \""<<o.palette_mode<<"\",\n  \"output_path\": \""<<json_escape(o.output.generic_string())<<"\"\n}\n";}
std::vector<Rect> detect_content_rows(const Image&source,int tolerance){Image im=source;remove_background(im,"corners",tolerance,0);std::vector<Rect>rows;bool active=false;int start=0,gap=0;for(int y=0;y<im.height;y++){bool occupied=false;for(int x=0;x<im.width;x+=2)if(im.pixel(x,y)[3]>8){occupied=true;break;}if(occupied){if(!active){active=true;start=y;}gap=0;}else if(active&&++gap>12){rows.push_back({0,start,im.width,y-gap-start+1});active=false;}}if(active)rows.push_back({0,start,im.width,im.height-start});return rows;}
}
