"""Independent GLB/config/scene verification and optional metadata refresh.

python tools/blender/check_f1_width_contract.py --update-reports
Needs the original backup and the Blender geometry_validation.json generated by
validate_f1_width.py. No game binaries or import caches are used.
"""
import argparse
import copy
import hashlib
import json
import math
import re
import struct
from pathlib import Path

ROOT=Path(__file__).resolve().parents[2]
ASSETS=ROOT/'game/assets/models/vehicles/f1-2026-2008'
BACKUP=Path('D:/Formula90s-backups/f1_2026_2008-width-1990')
REPORT=ROOT/'reports/vehicle-width-f1_2026_2008'
PHYSICS=ROOT/'game/data/vehicles/f1_2026_2008/f1_2026_2008_physics.json'
SCENE=ROOT/'game/scenes/vehicles/f1_2026_2008/f1_2026_2008_rust.tscn'

def read(path): return json.loads(path.read_text(encoding='utf-8-sig'))
def save(path,obj): path.write_text(json.dumps(obj,indent=2)+'\n',encoding='utf-8')
def sha(path): return hashlib.sha256(path.read_bytes()).hexdigest().upper()
def glb(path):
    raw=path.read_bytes(); magic,version,total=struct.unpack_from('<4sII',raw)
    assert magic==b'glTF' and version==2 and total==len(raw)
    size,kind=struct.unpack_from('<II',raw,12); assert kind==0x4e4f534a
    doc=json.loads(raw[20:20+size]); start=20+size
    size,kind=struct.unpack_from('<II',raw,start); assert kind==0x004e4942
    return doc,raw[start+8:start+8+size]
def accessor(doc,blob,index):
    a=doc['accessors'][index]; v=doc['bufferViews'][a['bufferView']]
    count={'SCALAR':1,'VEC2':2,'VEC3':3,'VEC4':4}[a['type']]
    code={5126:'f',5125:'I',5123:'H',5121:'B'}[a['componentType']]
    fmt='<'+str(count)+code; size=struct.calcsize(fmt)
    off=v.get('byteOffset',0)+a.get('byteOffset',0); stride=v.get('byteStride',size)
    return [struct.unpack_from(fmt,blob,off+i*stride) for i in range(a['count'])]

def main():
    parser=argparse.ArgumentParser(); parser.add_argument('--update-reports',action='store_true')
    args=parser.parse_args()
    metadata=read(ASSETS/'vehicle_metadata.json')
    metadata['dimensions_m'].update(overall_width=1.99,front_track_center=1.635,
        rear_track_center=1.590,rear_tire_width_visual=.400)
    for name,xyz in metadata['validation_datums'].items():
        if name.startswith('JNT_WHEEL_'): xyz[0]=math.copysign(.8175 if name[-2]=='F' else .795,xyz[0])
    for name in ('DATUM_WHEEL_INBOARD_FACE','DATUM_WHEEL_OUTBOARD_FACE'):
        metadata['wheel_rear_datums'][name][0]=math.copysign(.2,metadata['wheel_rear_datums'][name][0])
    metadata['assets']['source_blend']='source/f1_2026_2008_source.blend'
    results={}; stats={}; hashes={}
    for part in ('chassis','wheel_front','wheel_rear'):
        filename=f'f1_2026_2008_{part}.glb'
        old,ob=glb(BACKUP/'f1-2026-2008'/filename); new,nb=glb(ASSETS/filename)
        hashes[filename]=sha(ASSETS/filename)
        assert len(old['nodes'])==len(new['nodes'])
        expected=copy.deepcopy(old['nodes'])
        for n in expected:
            if part=='chassis' and n['name'].startswith('JNT_WHEEL_'):
                n['translation'][0]=metadata['validation_datums'][n['name']][0]
            elif part=='wheel_rear' and n['name'] in ('DATUM_WHEEL_INBOARD_FACE','DATUM_WHEEL_OUTBOARD_FACE'):
                n['translation'][0]*=.4/.38
        assert expected==new['nodes'],(part,'unexpected node, transform or hierarchy change')
        for key in ('meshes','materials','images','textures','samplers','scenes','scene','bufferViews'):
            assert old.get(key)==new.get(key),(part,key)
        mutable=set()
        for node in new['nodes']:
            if 'mesh' not in node: continue
            changed=part=='wheel_rear' or (part=='chassis' and node['name'].endswith('_SUSPENSION'))
            vertices=triangles=0
            for p in new['meshes'][node['mesh']]['primitives']:
                attrs=p['attributes']; assert 'NORMAL' in attrs and 'TEXCOORD_0' in attrs
                positions=accessor(new,nb,attrs['POSITION']); before=accessor(old,ob,attrs['POSITION'])
                assert all(a[1:]==b[1:] for a,b in zip(positions,before)),(part,node['name'],'longitudinal/height')
                assert all(math.isfinite(x) for row in positions for x in row)
                assert all(abs(sum(x*x for x in row)-1)<1e-4 for row in accessor(new,nb,attrs['NORMAL']))
                vertices+=len(positions)
                triangles+=new['accessors'][p['indices']]['count']//3
                if changed: mutable.update((attrs['POSITION'],attrs['NORMAL']))
            stats[part+'/'+node['name']]={'vertices_in_glb':vertices,'triangles':triangles}
        # Every byte outside the explicitly edited position/normal accessors stays
        # identical, including embedded textures, UVs, indices and other meshes.
        masked=bytearray(nb)
        for idx in mutable:
            a=new['accessors'][idx]; v=new['bufferViews'][a['bufferView']]
            off=v.get('byteOffset',0)+a.get('byteOffset',0); stride=v.get('byteStride',12)
            for i in range(a['count']): masked[off+i*stride:off+i*stride+12]=ob[off+i*stride:off+i*stride+12]
        assert bytes(masked)==ob,(part,'unrelated binary changes')
        datum_key='validation_datums' if part=='chassis' else part+'_datums'
        nodes={n['name']:n for n in new['nodes']}
        for name,xyz in metadata[datum_key].items():
            assert max(abs(a-b) for a,b in zip(nodes[name].get('translation',[0,0,0]),xyz))<1e-7
        results[part]={'sha256':hashes[filename], 'hierarchy_and_pivots_preserved':True,
            'longitudinal_and_vertical_coordinates_unchanged':True,
            'topology_materials_uvs_embedded_images_preserved':True,
            'unrelated_geometry_byte_identical':True,'datums_match_metadata':True,'passed':True}

    physics=read(PHYSICS); before=read(BACKUP/PHYSICS.name)
    before['geometry'].update(front_track=1.635,rear_track=1.590)
    before['tires']['rear']['width']=.400
    assert before==physics,'unexpected physics change'
    assert physics['geometry']['wheelbase']==3.23
    assert physics['tires']['front']['width']==.355
    scene=SCENE.read_text(); original=(BACKUP/SCENE.name).read_text()
    assert re.findall(r'^\[node .*$',scene,re.M)==re.findall(r'^\[node .*$',original,re.M)
    assert scene.split('[node ')[0]==original.split('[node ')[0],'collider resources changed'
    sections=re.split(r'(?=\[node )',scene)
    for name,half,z in [('FrontLeftWheel',-.8175,-1.615),('FrontRightWheel',.8175,-1.615),
                        ('RearLeftWheel',-.795,1.615),('RearRightWheel',.795,1.615)]:
        section=next(s for s in sections if s.startswith(f'[node name="{name}"'))
        pos=tuple(map(float,re.search(r'position = Vector3\(([^)]+)',section)[1].split(',')))
        assert pos==(half,0,z)
    for name in ('FrontLeftWheel','RearLeftWheel'):
        s=next(s for s in sections if s.startswith(f'[node name="Visual" parent="VehicleRigidBody/{name}"'))
        assert 'rotation = Vector3(0, 3.14159265, 0)' in s
    for name in ('FrontRightWheel','RearRightWheel'):
        s=next(s for s in sections if s.startswith(f'[node name="Orientation" type="Node3D" parent="VehicleRigidBody/{name}"'))
        assert 'rotation = Vector3(0, 0, 0)' in s
    geometry=read(REPORT/'geometry_validation.json')
    for path,digest in geometry['input_sha256'].items(): assert sha(ROOT/path)==digest,('stale Blender report',path)
    assert all(geometry['editable_source_checks'].values())
    assert all(abs(w-1.99)<1e-5 for w in geometry['measurements'].values())
    assert all(r['hub_intersecting_triangle_pairs']>0 for rows in geometry['suspension_contacts'].values() for r in rows)
    assert geometry['scene_raycasts_match_physics']
    validation={'schema':'formula90s/vehicle-width-validation/v1','glb_checks':results,
        'geometry_validation':geometry,'scene_hierarchy_and_colliders_preserved':True,
        'physics_changes_limited_to_tracks_and_rear_tire_width':True,
        'scope':'Static reference pose, zero steering and wheel roll; no driving or animated suspension validation.',
        'passed':True}
    if args.update_reports:
        save(ASSETS/'vehicle_metadata.json',metadata)
        manifest=read(ASSETS/'manifest.json'); manifest['physics_sha256']=sha(PHYSICS)
        for asset in manifest['geometry_assets'].values(): asset['sha256']=hashes[asset['path']]
        manifest['validation']={'status':'PASS','note':'Static width/GLB/config/scene checks rerun; see validation_report.json for scope.'}
        save(ASSETS/'manifest.json',manifest)
        save(ASSETS/'validation_report.json',validation)
        files=list(hashes)+['source/f1_2026_2008_source.blend','vehicle_metadata.json']
        save(ASSETS/'export_report.json',{'operation':'Blender lateral width edit preserving original GLB container',
            'files':{f:(ASSETS/f).stat().st_size for f in files},'mesh_stats':stats,
            'checks':results,'passed':True})
    else:
        assert read(ASSETS/'vehicle_metadata.json')==metadata
        manifest=read(ASSETS/'manifest.json'); assert manifest['physics_sha256']==sha(PHYSICS)
        for asset in manifest['geometry_assets'].values(): assert asset['sha256']==hashes[asset['path']]
        assert read(ASSETS/'validation_report.json')==validation
    print(json.dumps({'passed':True,'glb_checks':results,'width_m':geometry['measurements']},indent=2))

if __name__=='__main__': main()
