"""Build the canonical v10-v2 engine sample bank (schema 1) for f1_2030_v10.

Reads the raw engine, gearbox, limiter and backfire recordings from
game/sounds/banks/v10-v2-bank, normalizes every asset to 44.1 kHz mono PCM16,
rotates each engine loop to a common dominant-harmonic phase, places the
intermediate captures generated by tools/audio/generate_v10_engine_intermediates.py
between the low, med and high zones, copies the already prepared event assets
from the five engine sample bank, and writes manifest.json plus
source_inventory.json next to the derived WAVs.

Every configured engine cycle frequency is validated against a cepstral pitch
measurement of the raw capture, so a stale or mistyped reference fails the build
instead of shipping a mistuned loop.

The build is deterministic: identical sources produce byte-identical outputs.
Use --audit to inspect formats and measurements without writing, and --check to
validate an existing bank without rewriting anything.
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import math
import wave
from fractions import Fraction
from pathlib import Path

import numpy as np
from scipy.signal import butter, resample_poly, sosfiltfilt, welch
from tools.common.output_policy import validate_output_path

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_BANK_DIRECTORY = ROOT / "game/sounds/banks/v10-v2-bank"
EVENT_SOURCE_DIRECTORY = (
    ROOT / "game/audio/formula_one_2030_grand_prix_sampler/formula_one_2030_five_engine_sample_bank"
)
DEFAULT_REPORT_DIRECTORY = ROOT / "scratch/audio/v10-v2-bank"

SAMPLE_RATE = 44100
SCHEMA_VERSION = 1
TOOL_NAME = "tools/audio/build_canonical_v10_engine_bank.py"
TOOL_REVISION = 11
BANK_ID = "v10_v2_engine_bank"
EVENT_SELECTION_SEED = 1

MINIMUM_REVOLUTIONS_PER_MINUTE = 4500.0
MAXIMUM_REVOLUTIONS_PER_MINUTE = 18000.0
REVOLUTIONS_PER_MINUTE_PER_HERTZ = 120.0
CROSSFADE_CYCLE_COUNT = 4
TRANSITION_HALF_WIDTH_RATIO = 0.075
TRANSITION_BLEND_LAW = "smoothstep"
TRANSITION_GAIN_LAW = "equal_power"
TRANSITION_NARROW_HALF_WIDTH_RATIO = 0.04
LEVEL_BAND_HZ = (300.0, 6000.0)
REFERENCE_PHASE_SEARCH_FRAMES = 64
CEPSTRUM_FRAME_SIZE = 1 << 15
CEPSTRUM_MAXIMUM_FRAMES = 64
CEPSTRUM_SEARCH_MINIMUM_HERTZ = 25.0
CEPSTRUM_SEARCH_MAXIMUM_HERTZ = 250.0
REFERENCE_MEASUREMENT_TOLERANCE_RATIO = 0.015
REFERENCE_MEASUREMENT_MINIMUM_PROMINENCE_RATIO = 0.25
PREPARATION_RECIPE = "canonical_mono16_cycle_phase_rotated_v1"

ENGINE_SOURCES = [
    {
        "source_filename": "engine_idle.wav",
        "asset_id": "engine_idle_loop",
        "derived_filename": "engine_idle_loop.wav",
        "role": "engine_loop",
        "collection": "loops",
        "cycle_frequency_hertz": 4531.638723634397 / REVOLUTIONS_PER_MINUTE_PER_HERTZ,
        "reference_method": "authored_reference_integer_cycles",
        "zone_revolutions_per_minute": 4500.0,
    },
    {
        "source_filename": "engine_powered_low.wav",
        "asset_id": "engine_powered_low_loop",
        "derived_filename": "engine_powered_low_loop.wav",
        "role": "engine_loop",
        "collection": "loops",
        "cycle_frequency_hertz": 76.219,
        "reference_method": "measured_dominant_period_integer_cycles",
        "zone_revolutions_per_minute": 7500.0
    },
    {
        "source_filename": "engine_on_med.wav",
        "asset_id": "engine_mid_on_loop",
        "derived_filename": "engine_mid_on_loop.wav",
        "role": "engine_loop",
        "collection": "loops",
        "cycle_frequency_hertz": 106.265,
        "reference_method": "measured_dominant_period_integer_cycles",
        "zone_revolutions_per_minute": 11750.0
    },
    {
        "source_filename": "engine_powered_medium_high.wav",
        "asset_id": "engine_powered_medium_high_loop",
        "derived_filename": "engine_powered_medium_high_loop.wav",
        "role": "engine_loop",
        "collection": "loops",
        "cycle_frequency_hertz": 111.969,
        "reference_method": "measured_dominant_period_integer_cycles",
        "zone_revolutions_per_minute": 13750.0
    },
    {
        "source_filename": "engine_powered_high.wav",
        "asset_id": "engine_powered_high_loop",
        "derived_filename": "engine_powered_high_loop.wav",
        "role": "engine_loop",
        "collection": "loops",
        "cycle_frequency_hertz": 141.042,
        "reference_method": "measured_dominant_period_integer_cycles",
        "zone_revolutions_per_minute": 16250.0
    },
    {
        "source_filename": "engine_on_high.wav",
        "asset_id": "engine_powered_maximum_loop",
        "derived_filename": "engine_powered_maximum_loop.wav",
        "role": "engine_loop",
        "collection": "loops",
        "cycle_frequency_hertz": 148.889,
        "reference_method": "measured_dominant_period_integer_cycles",
        "zone_revolutions_per_minute": 17750.0
    },
    {
        "source_filename": "engine_off_low.wav",
        "asset_id": "engine_low_off_loop",
        "derived_filename": "engine_low_off_loop.wav",
        "role": "engine_coast_loop",
        "collection": "coast_loops",
        "cycle_frequency_hertz": 7922.604938131585 / REVOLUTIONS_PER_MINUTE_PER_HERTZ,
        "reference_method": "authored_reference_integer_cycles",
        "zone_revolutions_per_minute": 8000.0,
    },
    {
        "source_filename": "engine_off_med.wav",
        "asset_id": "engine_mid_off_loop",
        "derived_filename": "engine_mid_off_loop.wav",
        "role": "engine_coast_loop",
        "collection": "coast_loops",
        "cycle_frequency_hertz": 107.039,
        "reference_method": "measured_dominant_period_integer_cycles",
        "zone_revolutions_per_minute": 12800.0,
    },
    {
        "source_filename": "engine_off_maximum.wav",
        "asset_id": "engine_off_maximum_loop",
        "derived_filename": "engine_off_maximum_loop.wav",
        "role": "engine_coast_loop",
        "collection": "coast_loops",
        "cycle_frequency_hertz": 16542.744529515698 / REVOLUTIONS_PER_MINUTE_PER_HERTZ,
        "reference_method": "imported_reference_integer_cycles",
        "zone_revolutions_per_minute": 16500.0,
        "generation_recipe": "historical_gp3_coast_maximum_import",
    },
]

EVENT_SOURCE_BY_ASSET_ID = {
    "backfire_burst_3": "backfire_1.wav",
    "backfire_burst_4": "backfire_2.wav",
    "backfire_burst_5": "backfire_3.wav",
    "backfire_burst_6": "backfire_4.wav",
    "backfire_burst_7": "backfire_5.wav",
    "upshift_event": "gearup.wav",
    "downshift_event": "geardn.wav",
    "limiter_event": "limiter.wav",
}
CANONICAL_SOURCE_EVENT_IDENTIFIERS = frozenset({"upshift_event", "downshift_event", "limiter_event"})
CANONICAL_SOURCE_EVENT_RECIPE = "canonical_mono16_source_event_v1"


def sha256_bytes(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source_file:
        for chunk in iter(lambda: source_file.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def serialize_json(payload: object) -> bytes:
    return (json.dumps(payload, ensure_ascii=False, indent=2) + "\n").encode("utf-8")


def read_wave_mono(path: Path) -> tuple[int, np.ndarray]:
    with wave.open(str(path), "rb") as reader:
        channels = reader.getnchannels()
        sample_width = reader.getsampwidth()
        sample_rate = reader.getframerate()
        raw = reader.readframes(reader.getnframes())
    if sample_width == 1:
        samples = (np.frombuffer(raw, dtype=np.uint8).astype(np.float64) - 128.0) / 128.0
    elif sample_width == 2:
        samples = np.frombuffer(raw, dtype="<i2").astype(np.float64) / 32768.0
    elif sample_width == 3:
        octets = np.frombuffer(raw, dtype=np.uint8).reshape(-1, 3)
        values = (
            octets[:, 0].astype(np.int32)
            | (octets[:, 1].astype(np.int32) << 8)
            | (octets[:, 2].astype(np.int32) << 16)
        )
        values = np.where(values >= (1 << 23), values - (1 << 24), values).astype(np.float64)
        samples = values / 8388608.0
    elif sample_width == 4:
        samples = np.frombuffer(raw, dtype="<i4").astype(np.float64) / 2147483648.0
    else:
        raise ValueError(f"unsupported sample width {sample_width} bits in {path}")
    if channels > 1:
        samples = samples.reshape(-1, channels).mean(axis=1)
    return sample_rate, samples


def encode_pcm16(samples: np.ndarray) -> bytes:
    quantized = np.clip(np.round(samples * 32768.0), -32768.0, 32767.0).astype("<i2")
    return quantized.tobytes()


def wave_mono16_bytes(samples: np.ndarray) -> bytes:
    buffer = io.BytesIO()
    with wave.open(buffer, "wb") as writer:
        writer.setnchannels(1)
        writer.setsampwidth(2)
        writer.setframerate(SAMPLE_RATE)
        writer.writeframes(encode_pcm16(samples))
    return buffer.getvalue()


def rms_value(samples: np.ndarray) -> float:
    if samples.size == 0:
        return 0.0
    return float(math.sqrt(float(np.mean(np.square(samples)))))


def decibels_full_scale(value: float) -> float:
    return float(20.0 * math.log10(max(value, 1e-9)))


def band_rms(samples: np.ndarray, low_hz: float, high_hz: float) -> float:
    if samples.size < 16:
        return rms_value(samples)
    sos = butter(4, [low_hz, high_hz], btype="bandpass", fs=SAMPLE_RATE, output="sos")
    filtered = sosfiltfilt(sos, samples)
    return rms_value(np.asarray(filtered, dtype=np.float64))


def prepare_event_from_source(source_path: Path, event_template: dict) -> tuple[dict, bytes]:
    source_sample_rate, source_samples = read_wave_mono(source_path)
    if source_sample_rate <= 0:
        raise ValueError(f"{source_path} must have a positive sample rate")
    if source_sample_rate != SAMPLE_RATE:
        sample_rate_ratio = Fraction(SAMPLE_RATE, source_sample_rate)
        source_samples = resample_poly(
            source_samples,
            sample_rate_ratio.numerator,
            sample_rate_ratio.denominator,
        )
    if source_samples.size == 0:
        raise ValueError(f"{source_path} must contain audio samples")

    if event_template.get("role") == "limiter_event":
        source_peak = float(np.max(np.abs(source_samples)))
        if source_peak > 0.92:
            source_samples = source_samples * (0.92 / source_peak)

    derived_payload = wave_mono16_bytes(source_samples)
    prepared_event = {key: value for key, value in event_template.items()}
    prepared_event.update(
        {
            "source_filename": source_path.name,
            "source_sha256": sha256_file(source_path),
            "derived_sha256": sha256_bytes(derived_payload),
            "derived_frames": int(source_samples.size),
            "duration_seconds": float(source_samples.size / SAMPLE_RATE),
            "derived_rms_dbfs": decibels_full_scale(rms_value(source_samples)),
            "derived_peak_dbfs": decibels_full_scale(float(np.max(np.abs(source_samples)))),
            "derived_band_rms_300_6000": band_rms(source_samples, *LEVEL_BAND_HZ),
            "preparation_recipe": (
                "canonical_limiter_mono16_peak_headroom_v2"
                if event_template.get("role") == "limiter_event"
                else CANONICAL_SOURCE_EVENT_RECIPE
            ),
        }
    )
    return prepared_event, derived_payload


def loop_level(samples: np.ndarray) -> float:
    margin = len(samples) // 10
    core = samples[margin : len(samples) - margin] if len(samples) > 4 * margin else samples
    return rms_value(core)


def apply_playback_rate(samples: np.ndarray, ratio: float) -> np.ndarray:
    fraction = Fraction(1.0 / ratio).limit_denominator(4096)
    return resample_poly(samples, fraction.numerator, fraction.denominator)


def derive_reference(length: int, cycle_frequency_hertz: float) -> tuple[float, int]:
    cycles = max(1, round(length * cycle_frequency_hertz / SAMPLE_RATE))
    reference = cycles * SAMPLE_RATE / length * REVOLUTIONS_PER_MINUTE_PER_HERTZ
    return reference, cycles


def measure_seam(samples: np.ndarray) -> dict:
    deltas = np.abs(np.diff(np.round(samples * 32768.0).astype(np.int64)))
    if deltas.size == 0:
        return {"wrap_step": 0, "local_slope": 0, "seam_contract_holds": True}
    local_slope = int(np.sort(deltas)[int(deltas.size * 0.99)])
    wrap_step = abs(round(float(samples[0]) * 32768.0) - round(float(samples[-1]) * 32768.0))
    return {
        "wrap_step": wrap_step,
        "local_slope": local_slope,
        "seam_contract_holds": wrap_step <= max(2 * local_slope, 64),
    }


def rotate_to_reference_phase(samples: np.ndarray, frequency_hertz: float) -> tuple[np.ndarray, dict]:
    count = samples.size
    indices = np.arange(count)
    phasor = np.exp(-2j * np.pi * frequency_hertz * indices / SAMPLE_RATE)
    initial_phase = float(np.angle(np.dot(samples, phasor)))
    period_frames = SAMPLE_RATE / frequency_hertz
    target = (-initial_phase / (2.0 * np.pi)) * period_frames % period_frames
    base_shift = round(target)
    best_shift = base_shift % count
    best_step = None
    for offset in range(-REFERENCE_PHASE_SEARCH_FRAMES, REFERENCE_PHASE_SEARCH_FRAMES + 1):
        shift = (base_shift + offset) % count
        step = abs(float(samples[(shift - 1) % count] - samples[shift]))
        if best_step is None or step < best_step:
            best_step = step
            best_shift = shift
    rotated = np.concatenate([samples[best_shift:], samples[:best_shift]])
    residual = float(np.angle(np.dot(rotated, phasor)))
    metrics = {
        "loop_start_rotation_frames": int(best_shift),
        "dominant_harmonic_phase_before_radians": initial_phase,
        "dominant_harmonic_phase_residual_radians": residual,
        "rotation_wrap_step": float(best_step),
    }
    return rotated, metrics


def spectral_peaks(samples: np.ndarray, count: int = 16) -> list[float]:
    frequencies, power = welch(
        samples, fs=SAMPLE_RATE, nperseg=min(len(samples), 1 << 15), nfft=1 << 17
    )
    band = (frequencies >= 25.0) & (frequencies <= 1500.0)
    frequencies = frequencies[band]
    power = power[band]
    local_maxima = [
        index
        for index in range(1, len(power) - 1)
        if power[index] >= power[index - 1] and power[index] >= power[index + 1]
    ]
    local_maxima.sort(key=lambda index: power[index], reverse=True)
    picked: list[float] = []
    for index in local_maxima:
        frequency = float(frequencies[index])
        if any(abs(frequency - existing) / existing < 0.03 for existing in picked):
            continue
        picked.append(frequency)
        if len(picked) >= count:
            break
    return picked


def harmonic_comb_spacing(
    peaks: list[float], minimum_hz: float = 20.0, maximum_hz: float = 180.0
) -> tuple[float, float, int] | None:
    strong = peaks[:10]
    if not strong:
        return None
    for candidate in np.arange(maximum_hz, minimum_hz, -0.01):
        covered = 0
        total_error = 0.0
        for peak in strong:
            harmonic = max(1, round(peak / candidate))
            predicted = harmonic * candidate
            error = abs(peak - predicted) / peak
            if error <= 0.015:
                covered += 1
                total_error += error
        coverage = covered / max(len(strong), 1)
        if coverage >= 0.8 and total_error / max(covered, 1) <= 0.01:
            span = max(round(max(strong) / max(float(candidate), 1e-9)), 1)
            return float(candidate), float(coverage), span
    return None


def measure_dominant_period_frequency(samples: np.ndarray) -> float | None:
    centered = samples - float(np.mean(samples))
    count = centered.size
    if count < SAMPLE_RATE // 10:
        return None
    spectrum = np.fft.rfft(centered, n=2 * count)
    autocorrelation = np.fft.irfft(spectrum * np.conj(spectrum))[: SAMPLE_RATE // 20 + 1]
    autocorrelation /= max(float(autocorrelation[0]), 1e-9)
    low_lag = max(2, int(SAMPLE_RATE / 250.0))
    high_lag = int(SAMPLE_RATE / 20.0)
    window = autocorrelation[low_lag : high_lag + 1]
    if window.size == 0:
        return None
    lag = int(np.argmax(window)) + low_lag
    return SAMPLE_RATE / lag


def cepstral_frequency_spectrum(samples: np.ndarray) -> tuple[np.ndarray, np.ndarray] | None:
    centered = samples - float(np.mean(samples))
    frame_size = min(int(centered.size), CEPSTRUM_FRAME_SIZE)
    if frame_size < 1024:
        return None
    hop = frame_size // 2
    frame_count = 1 + max(0, (centered.size - frame_size) // hop)
    window = np.hanning(frame_size)
    accumulated = None
    for index in range(min(frame_count, CEPSTRUM_MAXIMUM_FRAMES)):
        segment = centered[index * hop : index * hop + frame_size] * window
        magnitude = np.abs(np.fft.rfft(segment)) + 1e-12
        cepstrum = np.fft.irfft(np.log(magnitude))
        accumulated = cepstrum if accumulated is None else accumulated + cepstrum
    cepstrum = accumulated / min(frame_count, CEPSTRUM_MAXIMUM_FRAMES)
    quefrency = np.arange(cepstrum.size)
    frequency = np.where(quefrency > 0, SAMPLE_RATE / np.maximum(quefrency, 1), 0.0)
    return frequency, cepstrum


def measure_cepstral_cycle_frequency(
    samples: np.ndarray, search_hertz: float
) -> tuple[float, float, float] | None:
    spectrum = cepstral_frequency_spectrum(samples)
    if spectrum is None:
        return None
    frequency, cepstrum = spectrum
    tolerance_band = (frequency >= search_hertz * (1.0 - REFERENCE_MEASUREMENT_TOLERANCE_RATIO)) & (
        frequency <= search_hertz * (1.0 + REFERENCE_MEASUREMENT_TOLERANCE_RATIO)
    )
    band_indices = np.flatnonzero(tolerance_band)
    if band_indices.size == 0:
        return None
    peak_index = int(band_indices[int(np.argmax(cepstrum[band_indices]))])
    interpolation_offset = 0.0
    if 0 < peak_index < cepstrum.size - 1:
        left_value = float(cepstrum[peak_index - 1])
        peak_value = float(cepstrum[peak_index])
        right_value = float(cepstrum[peak_index + 1])
        curvature = left_value - 2.0 * peak_value + right_value
        if curvature != 0.0:
            interpolation_offset = 0.5 * (left_value - right_value) / curvature
    measured_hertz = float(SAMPLE_RATE / (peak_index + interpolation_offset))
    search_band = (frequency >= CEPSTRUM_SEARCH_MINIMUM_HERTZ) & (
        frequency <= CEPSTRUM_SEARCH_MAXIMUM_HERTZ
    )
    reference_peak = float(np.max(cepstrum[search_band])) if bool(np.any(search_band)) else 0.0
    prominence = float(cepstrum[peak_index]) / max(reference_peak, 1e-9)
    return measured_hertz, float(cepstrum[peak_index]), prominence


def validate_engine_reference(samples: np.ndarray, entry: dict) -> dict:
    configured_hertz = float(entry["cycle_frequency_hertz"])
    measurement = measure_cepstral_cycle_frequency(samples, configured_hertz)
    if measurement is None:
        raise ValueError(
            f"{entry['source_filename']}: no cepstral pitch found near the configured "
            f"{configured_hertz:.4f} Hz reference"
        )
    measured_hertz, peak_value, prominence = measurement
    error_ratio = abs(measured_hertz - configured_hertz) / configured_hertz
    if error_ratio > REFERENCE_MEASUREMENT_TOLERANCE_RATIO:
        raise ValueError(
            f"{entry['source_filename']}: configured {configured_hertz:.4f} Hz differs from "
            f"the measured {measured_hertz:.4f} Hz by {error_ratio * 100.0:.3f}%"
        )
    if prominence < REFERENCE_MEASUREMENT_MINIMUM_PROMINENCE_RATIO:
        raise ValueError(
            f"{entry['source_filename']}: configured {configured_hertz:.4f} Hz is not the "
            f"dominant engine comb (prominence {prominence:.3f}); the capture plays at "
            f"{measured_hertz:.4f} Hz"
        )
    return {
        "measured_cepstral_spacing_hertz": measured_hertz,
        "cepstral_spacing_peak": peak_value,
        "cepstral_spacing_prominence": prominence,
        "configured_reference_error_ratio": error_ratio,
    }


def transition(from_id: str, to_id: str, start: float, end: float, compensation: float) -> dict:
    center = (start + end) * 0.5
    return {
        "from_loop_id": from_id,
        "to_loop_id": to_id,
        "start_revolutions_per_minute": float(start),
        "end_revolutions_per_minute": float(end),
        "center_revolutions_per_minute": float(center),
        "half_width_revolutions_per_minute": float((end - start) * 0.5),
        "blend_law": TRANSITION_BLEND_LAW,
        "gain_law": TRANSITION_GAIN_LAW,
        "measured_level_compensation_db": float(compensation),
        "applied_level_step_db": 0.0,
    }


def prepare_engine_loop(source_directory: Path, entry: dict) -> tuple[dict, np.ndarray, bytes]:
    source_path = source_directory / entry["source_filename"]
    if not source_path.is_file():
        raise FileNotFoundError(f"missing engine source: {source_path}")
    source_hash = sha256_file(source_path)
    sample_rate, samples = read_wave_mono(source_path)
    if sample_rate != SAMPLE_RATE:
        raise ValueError(f"{source_path} must be {SAMPLE_RATE} Hz, found {sample_rate}")
    validate_engine_reference(samples, entry)
    seam_before = measure_seam(samples)
    reference, cycles = derive_reference(samples.size, entry["cycle_frequency_hertz"])
    rotated, rotation_metrics = rotate_to_reference_phase(samples, reference / REVOLUTIONS_PER_MINUTE_PER_HERTZ)
    seam_after = measure_seam(rotated)
    derived_payload = wave_mono16_bytes(rotated)
    crossfade_frames = max(
        32,
        round(CROSSFADE_CYCLE_COUNT * SAMPLE_RATE / (reference / REVOLUTIONS_PER_MINUTE_PER_HERTZ)),
    )
    peaks = spectral_peaks(rotated)
    comb = harmonic_comb_spacing(peaks)
    asset = {
        "id": entry["asset_id"],
        "role": entry["role"],
        "collection": entry["collection"],
        "source_filename": entry["source_filename"],
        "source_sha256": source_hash,
        "derived_filename": entry["derived_filename"],
        "derived_sha256": sha256_bytes(derived_payload),
        "derived_frames": int(rotated.size),
        "derived_rms_dbfs": decibels_full_scale(rms_value(rotated)),
        "derived_peak_dbfs": decibels_full_scale(float(np.max(np.abs(rotated)))),
        "derived_band_rms_300_6000": band_rms(rotated, *LEVEL_BAND_HZ),
        "comb_spacing_hz": reference / REVOLUTIONS_PER_MINUTE_PER_HERTZ,
        "comb_fit_confidence": float(comb[1]) if comb else None,
        "comb_harmonic_span": int(comb[2]) if comb else None,
        "reference_method": entry["reference_method"],
        "reference_rpm_per_hz": REVOLUTIONS_PER_MINUTE_PER_HERTZ,
        "reference_revolutions_per_minute": float(reference),
        "integer_cycle_count": int(cycles),
        "preparation_recipe": PREPARATION_RECIPE,
        "loop_start_frame": 0,
        "loop_end_frame_exclusive": int(rotated.size),
        "loop_crossfade_frames": int(crossfade_frames),
        "seam_before_preparation": seam_before,
        "seam_after_preparation": seam_after,
        **rotation_metrics,
    }
    if "generation_recipe" in entry:
        asset["generation_recipe"] = entry["generation_recipe"]
    return asset, rotated, derived_payload


def set_zone_revolutions_per_minute(asset: dict, entry: dict) -> None:
    if entry["zone_revolutions_per_minute"] is not None:
        asset["zone_revolutions_per_minute"] = float(entry["zone_revolutions_per_minute"])
    else:
        asset["zone_revolutions_per_minute"] = float(
            round(asset["reference_revolutions_per_minute"] / 100.0) * 100
        )


def transition_half_widths(zones: list[float]) -> list[float]:
    centers = [
        math.sqrt(zones[index] * zones[index + 1]) for index in range(len(zones) - 1)
    ]
    widths = [TRANSITION_HALF_WIDTH_RATIO] * len(centers)
    for index in range(len(centers) - 1):
        safe_width = (centers[index + 1] - centers[index]) / (
            centers[index + 1] + centers[index]
        )
        if safe_width < TRANSITION_HALF_WIDTH_RATIO:
            if safe_width < TRANSITION_NARROW_HALF_WIDTH_RATIO:
                raise ValueError(
                    f"transition windows cannot fit between zones {zones[index:index + 3]}"
                )
            widths[index] = min(widths[index], TRANSITION_NARROW_HALF_WIDTH_RATIO)
            widths[index + 1] = min(
                widths[index + 1], TRANSITION_NARROW_HALF_WIDTH_RATIO
            )
    return widths


def build_collection(
    assets: list[dict],
    audio: dict[str, np.ndarray],
    coverage: dict,
    transition_windows: list[tuple[float, float]] | None = None,
) -> list[dict]:
    transitions: list[dict] = []
    widths = (
        [0.0] * (len(assets) - 1)
        if transition_windows is not None
        else transition_half_widths([asset["zone_revolutions_per_minute"] for asset in assets])
    )
    for index in range(len(assets) - 1):
        center = math.sqrt(
            assets[index]["zone_revolutions_per_minute"]
            * assets[index + 1]["zone_revolutions_per_minute"]
        )
        half_width = center * widths[index]
        start, end = (
            transition_windows[index]
            if transition_windows is not None
            else (center - half_width, center + half_width)
        )
        transitions.append(
            transition(
                assets[index]["id"], assets[index + 1]["id"], start, end, 0.0
            )
        )
    gains = [1.0]
    for index, item in enumerate(transitions):
        center = item["center_revolutions_per_minute"]
        left_rate = center / assets[index]["reference_revolutions_per_minute"]
        right_rate = center / assets[index + 1]["reference_revolutions_per_minute"]
        left_level = loop_level(apply_playback_rate(audio[assets[index]["id"]], left_rate))
        right_level = loop_level(apply_playback_rate(audio[assets[index + 1]["id"]], right_rate))
        ratio = left_level / max(right_level, 1e-9)
        item["measured_level_compensation_db"] = float(20.0 * math.log10(max(ratio, 1e-9)))
        item["applied_level_step_db"] = 0.0
        assets[index]["boundary_level_rms"] = float(left_level)
        assets[index + 1]["boundary_level_rms"] = float(right_level)
        gains.append(gains[index] * ratio)
    normalization = max(gains) if max(gains) > 0.0 else 1.0
    for asset, gain in zip(assets, gains):
        asset["calibrated_gain"] = float(gain / normalization)
    for index, asset in enumerate(assets):
        start = (
            coverage["minimum_revolutions_per_minute"]
            if index == 0
            else transitions[index - 1]["start_revolutions_per_minute"]
        )
        end = (
            coverage["maximum_revolutions_per_minute"]
            if index + 1 == len(assets)
            else transitions[index]["end_revolutions_per_minute"]
        )
        reference = asset["reference_revolutions_per_minute"]
        asset["active_coverage_revolutions_per_minute"] = [float(start), float(end)]
        asset["valid_playback_rate_min"] = float(min(start, end) / reference * (1.0 - 1e-6))
        asset["valid_playback_rate_max"] = float(max(start, end) / reference * (1.0 + 1e-6))
    return transitions


POWERED_ENGINE_PRESENCE_CURVES = {'engine_idle_loop': [(4500.0, 1.0), (4800.0, 1.0), (5600.0, 0.0)],
 'engine_powered_low_loop': [(4800.0, 0.0), (5600.0, 1.0), (9500.0, 1.0), (11500.0, 0.0)],
 'engine_mid_on_loop': [(9500.0, 0.0), (11500.0, 1.0), (12000.0, 1.0), (13000.0, 0.0)],
 'engine_powered_medium_high_loop': [(12000.0, 0.0),
                                     (13000.0, 1.0),
                                     (14500.0, 1.0),
                                     (16000.0, 0.0)],
 'engine_powered_high_loop': [(14500.0, 0.0), (16000.0, 1.0), (16500.0, 1.0), (17500.0, 0.0)],
 'engine_powered_maximum_loop': [(16500.0, 0.0), (17500.0, 1.0), (18000.0, 1.0)]}


POWERED_ENGINE_CALIBRATED_GAINS = {'engine_idle_loop': 1.0,
 'engine_mid_on_loop': 0.756190541567477,
 'engine_powered_maximum_loop': 0.6050664636291578}

COAST_ENGINE_CALIBRATION_ANCHOR_GAIN = 0.7889246022157463


def apply_powered_engine_presence_curves(assets: list[dict]) -> None:
    medium_asset = next(asset for asset in assets if asset["id"] == "engine_mid_on_loop")
    reference_band_level = medium_asset["derived_band_rms_300_6000"]
    reference_gain = POWERED_ENGINE_CALIBRATED_GAINS["engine_mid_on_loop"]
    for asset in assets:
        presence_points = POWERED_ENGINE_PRESENCE_CURVES[asset["id"]]
        asset["presence_curve"] = [
            {"revolutions_per_minute": revolutions_per_minute, "relative_weight": relative_weight}
            for revolutions_per_minute, relative_weight in presence_points
        ]
        asset["calibrated_gain"] = POWERED_ENGINE_CALIBRATED_GAINS.get(
            asset["id"], reference_gain * reference_band_level / max(asset["derived_band_rms_300_6000"], 1e-9),
        )
        start = presence_points[0][0]
        end = presence_points[-1][0]
        reference = asset["reference_revolutions_per_minute"]
        asset["active_coverage_revolutions_per_minute"] = [start, end]
        asset["valid_playback_rate_min"] = start / reference * (1.0 - 1e-6)
        asset["valid_playback_rate_max"] = end / reference * (1.0 + 1e-6)


def remove_internal_fields(asset: dict) -> dict:
    internal_fields = {"collection", "generation_recipe"}
    return {key: value for key, value in asset.items() if key not in internal_fields}


def build_manifest(bank_directory: Path, event_source_directory: Path) -> tuple[dict, dict[str, bytes]]:
    coverage = {
        "minimum_revolutions_per_minute": MINIMUM_REVOLUTIONS_PER_MINUTE,
        "maximum_revolutions_per_minute": MAXIMUM_REVOLUTIONS_PER_MINUTE,
    }
    prepared_assets: list[dict] = []
    loop_audio: dict[str, np.ndarray] = {}
    loop_payloads: dict[str, bytes] = {}
    for entry in ENGINE_SOURCES:
        asset, rotated, derived_payload = prepare_engine_loop(bank_directory, entry)
        set_zone_revolutions_per_minute(asset, entry)
        prepared_assets.append(asset)
        loop_audio[asset["id"]] = rotated
        loop_payloads[asset["id"]] = derived_payload
    powered = [asset for asset in prepared_assets if asset["collection"] == "loops"]
    coast = [asset for asset in prepared_assets if asset["collection"] == "coast_loops"]
    for collection in (powered, coast):
        zones = [asset["zone_revolutions_per_minute"] for asset in collection]
        if zones != sorted(zones) or len(set(zones)) != len(zones):
            raise ValueError(f"engine zones must be strictly ascending: {zones}")
    powered_transitions = build_collection(
        powered, loop_audio, coverage,
        [(4800.0, 5600.0), (9500.0, 11500.0), (12000.0, 13000.0), (14500.0, 16000.0), (16500.0, 17500.0)],
    )
    apply_powered_engine_presence_curves(powered)
    coast_transitions = build_collection(
        coast, loop_audio, coverage, [(9500.0, 11500.0), (14000.0, 16000.0)],
    )
    for coast_asset in coast:
        coast_asset["calibrated_gain"] *= COAST_ENGINE_CALIBRATION_ANCHOR_GAIN

    source_manifest = json.loads(
        (event_source_directory / "manifest.json").read_text(encoding="utf-8")
    )
    events = []
    inventory_events = []
    event_audio: dict[str, bytes] = {}
    for event in source_manifest["events"]:
        asset_id = event["id"]
        if asset_id not in EVENT_SOURCE_BY_ASSET_ID:
            raise ValueError(f"unexpected event asset {asset_id}")
        canon_source_name = EVENT_SOURCE_BY_ASSET_ID[asset_id]
        canon_source_path = bank_directory / canon_source_name
        if asset_id == "limiter_event":
            event = {**event, "derived_filename": "limiter_cut_loop.wav"}
        if asset_id in CANONICAL_SOURCE_EVENT_IDENTIFIERS:
            copied, payload = prepare_event_from_source(canon_source_path, event)
            preparation_source_bank = bank_directory.name
        else:
            event_path = event_source_directory / event["derived_filename"]
            payload = event_path.read_bytes()
            if sha256_bytes(payload) != event["derived_sha256"]:
                raise ValueError(f"prepared event hash mismatch: {event_path}")
            copied = {key: value for key, value in event.items()}
            copied["source_filename"] = canon_source_name
            copied["source_sha256"] = sha256_file(canon_source_path)
            preparation_source_bank = event_source_directory.name
        events.append(copied)
        event_audio[event["derived_filename"]] = payload
        inventory_events.append(
            {
                "asset_id": asset_id,
                "role": event["role"],
                "derived_filename": event["derived_filename"],
                "derived_sha256": copied["derived_sha256"],
                "source_filename": canon_source_name,
                "source_sha256": copied["source_sha256"],
                "preparation_recipe": copied["preparation_recipe"],
                "preparation_source_bank": preparation_source_bank,
            }
        )

    engine_source_inventory = []
    for asset in prepared_assets:
        source_record = {
            "role": asset["id"],
            "source_path": (bank_directory / asset["source_filename"]).relative_to(ROOT).as_posix(),
            "source_sha256": asset["source_sha256"],
            "runtime_asset_id": asset["id"],
            "runtime_filename": asset["derived_filename"],
            "runtime_sha256": asset["derived_sha256"],
            "derived_frames": asset["derived_frames"],
            "reference_revolutions_per_minute": asset["reference_revolutions_per_minute"],
            "zone_revolutions_per_minute": asset["zone_revolutions_per_minute"],
            "integer_cycle_count": asset["integer_cycle_count"],
            "loop_crossfade_frames": asset["loop_crossfade_frames"],
            "loop_start_rotation_frames": asset["loop_start_rotation_frames"],
            "preparation_recipe": PREPARATION_RECIPE,
        }
        if "generation_recipe" in asset:
            source_record["generation_recipe"] = asset["generation_recipe"]
        engine_source_inventory.append(source_record)
    source_inventory = {
        "bank_id": BANK_ID,
        "engine_source_directory": bank_directory.relative_to(ROOT).as_posix(),
        "engine_sources": engine_source_inventory,
        "preserved_events": inventory_events,
    }
    inventory_bytes = serialize_json(source_inventory)
    event_groups = source_manifest["event_groups"]
    for group in event_groups:
        if group["id"] == "limiter":
            group["trigger_event"] = "limiter_cut_window"

    manifest = {
        "schema_version": SCHEMA_VERSION,
        "bank_id": BANK_ID,
        "preparation_tool": TOOL_NAME,
        "preparation_tool_revision": TOOL_REVISION,
        "source_inventory_sha256": sha256_bytes(inventory_bytes),
        "output_sample_rate": SAMPLE_RATE,
        "event_selection_seed": EVENT_SELECTION_SEED,
        "coverage": coverage,
        "loops": [remove_internal_fields(asset) for asset in powered],
        "transitions": powered_transitions,
        "coast_loops": [remove_internal_fields(asset) for asset in coast],
        "coast_transitions": coast_transitions,
        "events": events,
        "event_groups": event_groups,
        "event_trigger_policy": source_manifest["event_trigger_policy"],
        "reference_ladder": {
            "method": "authored_and_measured_reference_integer_cycles",
            "revolutions_per_minute_per_hertz": REVOLUTIONS_PER_MINUTE_PER_HERTZ,
            "anchor_center_revolutions_per_minute": math.sqrt(
                MINIMUM_REVOLUTIONS_PER_MINUTE * MAXIMUM_REVOLUTIONS_PER_MINUTE
            ),
            "engine_references_revolutions_per_minute": {
                asset["id"]: asset["reference_revolutions_per_minute"] for asset in prepared_assets
            },
            "engine_zones_revolutions_per_minute": {
                asset["id"]: asset["zone_revolutions_per_minute"] for asset in prepared_assets
            },
        },
        "engine_source_selection": engine_source_inventory,
    }
    manifest_bytes = serialize_json(manifest)

    outputs = {
        "manifest.json": manifest_bytes,
        "source_inventory.json": inventory_bytes,
    }
    for asset in prepared_assets:
        outputs[asset["derived_filename"]] = loop_payloads[asset["id"]]
    for filename, payload in event_audio.items():
        outputs[filename] = payload
    return manifest, outputs


def build_report(manifest: dict, bank_directory: Path) -> dict:
    entries = []
    for loop in manifest["loops"] + manifest["coast_loops"]:
        source_path = bank_directory / loop["source_filename"]
        sample_rate, samples = read_wave_mono(source_path)
        with wave.open(str(source_path), "rb") as reader:
            source_channels = reader.getnchannels()
            source_sample_width_bits = reader.getsampwidth() * 8
        entries.append(
            {
                "asset_id": loop["id"],
                "source_filename": loop["source_filename"],
                "source_sample_rate": sample_rate,
                "source_channels": source_channels,
                "source_sample_width_bits": source_sample_width_bits,
                "source_frames": int(samples.size),
                "derived_filename": loop["derived_filename"],
                "derived_frames": loop["derived_frames"],
                "reference_revolutions_per_minute": loop["reference_revolutions_per_minute"],
                "zone_revolutions_per_minute": loop["zone_revolutions_per_minute"],
                "integer_cycle_count": loop["integer_cycle_count"],
                "loop_crossfade_frames": loop["loop_crossfade_frames"],
                "loop_start_rotation_frames": loop["loop_start_rotation_frames"],
                "seam_before_preparation": loop["seam_before_preparation"],
                "seam_after_preparation": loop["seam_after_preparation"],
            }
        )
    return {"bank_id": manifest["bank_id"], "engine_loops": entries}


def source_format_table(bank_directory: Path) -> list[dict]:
    table = []
    for path in sorted(bank_directory.glob("*.wav")):
        if path.name.endswith("_loop.wav") or path.name in (
            "upshift_event.wav",
            "downshift_event.wav",
            "limiter_event.wav",
            "limiter_cut_loop.wav",
        ) or path.name.startswith("backfire_burst_"):
            continue
        with wave.open(str(path), "rb") as reader:
            table.append(
                {
                    "file": path.name,
                    "channels": reader.getnchannels(),
                    "sample_width_bits": reader.getsampwidth() * 8,
                    "sample_rate": reader.getframerate(),
                    "frames": reader.getnframes(),
                    "duration_seconds": reader.getnframes() / reader.getframerate(),
                }
            )
    return table


def audit(bank_directory: Path, report_directory: Path) -> int:
    formats = source_format_table(bank_directory)
    measurements = []
    for entry in ENGINE_SOURCES:
        path = bank_directory / entry["source_filename"]
        sample_rate, samples = read_wave_mono(path)
        reference, cycles = derive_reference(samples.size, entry["cycle_frequency_hertz"])
        rotated, rotation_metrics = rotate_to_reference_phase(samples, reference / REVOLUTIONS_PER_MINUTE_PER_HERTZ)
        peaks = spectral_peaks(rotated)
        comb = harmonic_comb_spacing(peaks)
        cepstral = measure_cepstral_cycle_frequency(samples, entry["cycle_frequency_hertz"])
        measurements.append(
            {
                "source_filename": entry["source_filename"],
                "sample_rate": sample_rate,
                "frames": int(samples.size),
                "configured_cycle_frequency_hertz": entry["cycle_frequency_hertz"],
                "measured_dominant_period_hertz": measure_dominant_period_frequency(rotated),
                "measured_comb_spacing_hertz": comb[0] if comb else None,
                "measured_cepstral_spacing_hertz": cepstral[0] if cepstral else None,
                "cepstral_spacing_prominence": cepstral[2] if cepstral else None,
                "configured_reference_error_ratio": (
                    abs(cepstral[0] - entry["cycle_frequency_hertz"]) / entry["cycle_frequency_hertz"]
                    if cepstral
                    else None
                ),
                "derived_reference_revolutions_per_minute": reference,
                "integer_cycle_count": cycles,
                "seam_before_preparation": measure_seam(samples),
                "seam_after_preparation": measure_seam(rotated),
                **rotation_metrics,
            }
        )
    print("source format table")
    for row in formats:
        print(
            f"  {row['file']:24s} channels={row['channels']} bits={row['sample_width_bits']:2d} "
            f"rate={row['sample_rate']} frames={row['frames']} seconds={row['duration_seconds']:.3f}"
        )
    print("engine loop measurements")
    for row in measurements:
        dominant = row["measured_dominant_period_hertz"]
        comb = row["measured_comb_spacing_hertz"]
        cepstral = row["measured_cepstral_spacing_hertz"]
        prominence = row["cepstral_spacing_prominence"]
        error_ratio = row["configured_reference_error_ratio"]
        print(
            f"  {row['source_filename']:22s} configured={row['configured_cycle_frequency_hertz']:9.4f}Hz "
            f"dominant={dominant if dominant is None else round(dominant, 4)}Hz "
            f"comb={comb if comb is None else round(comb, 4)}Hz "
            f"cepstral={cepstral if cepstral is None else round(cepstral, 4)}Hz "
            f"prominence={prominence if prominence is None else round(prominence, 3)} "
            f"error={error_ratio if error_ratio is None else round(error_ratio, 5)} "
            f"reference={row['derived_reference_revolutions_per_minute']:9.3f}rpm cycles={row['integer_cycle_count']} "
            f"seam_before={row['seam_before_preparation']} seam_after={row['seam_after_preparation']}"
        )
    report_directory.mkdir(parents=True, exist_ok=True)
    (report_directory / "audit.json").write_bytes(
        serialize_json({"source_formats": formats, "engine_measurements": measurements})
    )
    print(f"audit written to {report_directory / 'audit.json'}")
    return 0


def main() -> int:
    argument_parser = argparse.ArgumentParser()
    argument_parser.add_argument("--bank-directory", type=Path, default=DEFAULT_BANK_DIRECTORY)
    argument_parser.add_argument("--event-source-directory", type=Path, default=EVENT_SOURCE_DIRECTORY)
    argument_parser.add_argument("--report-directory", type=Path, default=DEFAULT_REPORT_DIRECTORY)
    argument_parser.add_argument("--audit", action="store_true")
    argument_parser.add_argument("--check", action="store_true")
    arguments = argument_parser.parse_args()

    if arguments.audit:
        return audit(arguments.bank_directory, arguments.report_directory)

    manifest, outputs = build_manifest(arguments.bank_directory, arguments.event_source_directory)
    if arguments.check:
        for filename, expected in outputs.items():
            path = arguments.bank_directory / filename
            if not path.is_file() or path.read_bytes() != expected:
                raise SystemExit(f"canonical bank output differs from reproducible build: {path}")
        print(f"verified {len(outputs)} canonical bank files in {arguments.bank_directory}")
        return 0

    for filename in outputs:
        validate_output_path(ROOT, arguments.bank_directory / filename, "promote")
    validate_output_path(ROOT, arguments.report_directory / "build_report.json", "preview")
    retired_limiter_recording_path = arguments.bank_directory / "limiter_event.wav"
    validate_output_path(ROOT, retired_limiter_recording_path, "promote")
    arguments.bank_directory.mkdir(parents=True, exist_ok=True)
    for filename, payload in outputs.items():
        (arguments.bank_directory / filename).write_bytes(payload)
    if retired_limiter_recording_path.exists():
        retired_limiter_recording_path.unlink()
    arguments.report_directory.mkdir(parents=True, exist_ok=True)
    (arguments.report_directory / "build_report.json").write_bytes(
        serialize_json(build_report(manifest, arguments.bank_directory))
    )
    print(f"prepared {len(outputs)} canonical bank files in {arguments.bank_directory}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
