#!/usr/bin/env python3
"""Build engine_int instrument tables from the FMOD bank dump (catalog v2).

Parses .codex_tmp/v10_v2_bank_dump_v2.txt and emits
game/sounds/runtime/catalog.v2.json with the exact per-instrument automation
tables (RPM windows, base gains, pitch curve, autopitch refs) for the R25
engine family, replacing the approximation tables in commands.rs.

Verifiable source: the dump is generated by the offline FModBankParser
(.codex_tmp/fmod_parser) from banks/v10_v2/vrc_2005_renault_r25.bank.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DUMP = ROOT / ".codex_tmp" / "v10_v2_bank_dump_v2.txt"
OUT = ROOT / "game" / "sounds" / "runtime" / "catalog.v2.json"

RPM_PARAM_INT = "80f9f0a4-44ea-45a4-ab71-26af7dddd708"
RPM_PARAM_EXT = "5be433df-2511-4c1e-810f-e8e0601a6c9f"
DRIVETRAIN_PARAM = "88a2c2e0-93c7-40ea-adc6-f07cdd625bbb"


def load_sections(path: Path) -> dict[str, list[str]]:
    raw = path.read_bytes()
    if raw[:2] in (b"\xff\xfe", b"\xfe\xff"):
        text = raw.decode("utf-16")
    else:
        text = raw.decode("utf-8", errors="replace")
    sections: dict[str, list[str]] = {}
    cur = ""
    for line0 in text.splitlines():
        line = line0.rstrip("\r")
        m = re.match(r"^([A-Z_]+)_(BEGIN|END)$", line)
        if m:
            cur = m.group(1) if m.group(2) == "BEGIN" else ""
            continue
        if cur:
            sections.setdefault(cur, []).append(line)
    return sections


def main() -> int:
    if not DUMP.exists():
        print(f"missing dump: {DUMP}", file=sys.stderr)
        return 1
    sec = load_sections(DUMP)

    instruments: dict[str, dict] = {}
    for line in sec.get("INSTRUMENTS", []):
        m = re.match(
            r"^([0-9a-f-]+)\|wave\|([^|]+)\|vol=([^|]+)\|pitch=([^|]+)\|loops=([^|]+)\|"
            r"chance=([^|]+)\|control=([^|]+)\|timeline=([^|]+)\|auto_pitch_ref=([^|]+)\|"
            r"auto_pitch_min=([^|]+)\|seek=([^|]+)",
            line,
        )
        if not m:
            continue
        g, sample, vol, pitch, loops, chance, control, tl, ref, amin, seek = m.groups()
        instruments[g] = {
            "sample": sample,
            "vol": float(vol),
            "pitch": float(pitch),
            "loops": int(loops),
            "control": control,
            "auto_pitch_ref": float(ref),
            "auto_pitch_min": float(amin),
            "seek": float(seek),
        }

    controllers: dict[str, dict] = {}
    for line in sec.get("CONTROLLERS", []):
        m = re.match(
            r"^([0-9a-f-]+)\|property=([0-9a-f-]+)\|curve=([0-9a-f-]+)\|index=(\d+)", line
        )
        if not m:
            continue
        cg, prop, curve, idx = m.groups()
        controllers[cg] = {"property": prop, "curve": curve, "index": int(idx)}

    curves: dict[str, list[list[float]]] = {}
    for line in sec.get("CURVES", []):
        m = re.match(r"^([0-9a-f-]+)\|owner=[0-9a-f-]+\|points=(.*)$", line)
        if not m:
            continue
        cg, points = m.groups()
        curves[cg] = [
            [float(a), float(b), float(c), float(d)]
            for p in points.split(";")
            if (parts := p.split(":"))
            and len(parts) == 4
            and (a := parts[0])
            and (b := parts[1])
            and (c := parts[2])
            and (d := parts[3])
        ]

    def windows_for(instr_guid: str) -> list[dict]:
        out = []
        for ctrl in controllers.values():
            if ctrl["property"] != instr_guid:
                continue
            pts = curves.get(ctrl["curve"], [])
            if not pts:
                continue
            entry = {"points": pts}
            y0, y1 = pts[0][1], pts[-1][1]
            if y0 < y1:
                entry["role"] = "enter"
            else:
                entry["role"] = "exit"
            out.append(entry)
        out.sort(key=lambda w: w["points"][0][0])
        return out

    def pitch_for(instr_guid: str) -> list[list[float]] | None:
        for ctrl in controllers.values():
            if ctrl["property"] == instr_guid and ctrl["index"] == 0:
                pts = curves.get(ctrl["curve"])
                if pts and pts[0][1] <= 0.0:
                    return pts
        return None

    engine_int = []
    engine_ext = []
    transmission = []
    for g, inst in sorted(instruments.items(), key=lambda kv: kv[1]["sample"]):
        if inst["control"] == RPM_PARAM_INT and inst["sample"].startswith("r25 int"):
            w = windows_for(g)
            if not w:
                continue
            engine_int.append(
                {
                    "instrument": g,
                    "sample": inst["sample"],
                    "vol_db": inst["vol"],
                    "base_pitch_st": inst["pitch"],
                    "loop": inst["loops"],
                    "auto_pitch_ref": inst["auto_pitch_ref"],
                    "seek": inst["seek"],
                    "windows": w,
                }
            )
        elif inst["control"] == RPM_PARAM_EXT and (
            inst["sample"].startswith("r25 ext") or inst["sample"].startswith("f2000")
        ):
            w = windows_for(g)
            if not w:
                continue
            engine_ext.append(
                {
                    "instrument": g,
                    "sample": inst["sample"],
                    "vol_db": inst["vol"],
                    "base_pitch_st": inst["pitch"],
                    "loop": inst["loops"],
                    "auto_pitch_ref": inst["auto_pitch_ref"],
                    "seek": inst["seek"],
                    "windows": w,
                }
            )
        elif inst["control"] == DRIVETRAIN_PARAM:
            w = windows_for(g)
            transmission.append(
                {
                    "instrument": g,
                    "sample": inst["sample"],
                    "vol_db": inst["vol"],
                    "base_pitch_st": inst["pitch"],
                    "loop": inst["loops"],
                    "auto_pitch_ref": inst["auto_pitch_ref"],
                    "windows": w or [],
                }
            )

    catalog = {
        "schema_version": 2,
        "bank": {
            "name": "vrc_2005_renault_r25.bank",
            "sha256": "6CC0E286E382BB71F1D8169CC8C7F7EA86D2A126AA790B4B52B9E92203843D03",
        },
        "pitch_automation_rpms": [
            [5281.519, -11.444349, -0.33287054, 0],
            [15687.891, 0.0, 0.0, 0],
        ],
        "engine_int": engine_int,
        "engine_ext": engine_ext,
        "transmission": transmission,
    }
    OUT.write_text(json.dumps(catalog, indent=2), encoding="utf-8")
    print(f"wrote {OUT} (engine_int={len(engine_int)}, engine_ext={len(engine_ext)}, "
          f"transmission={len(transmission)})")
    return 0


if __name__ == "__main__":
    sys.exit(main())